metrotranscom/doorway

backend/core/.env.template, backend/core/package.json, backend/core/src/listings/listings.controller.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts, backend/core/src/shared/shared.module.ts, backend/core/test/listings/listings.e2e-spec.ts, backend/core/types/src/backend-swagger.ts, yarn.lock
Continues work on #11 and implements some changes proposed in the jurisdiction DD. Adds a new backend/core API endpoint, `listings/bloom/:id`. This is the version of `listings/:id` that currently exists but instead of looking in our own postgres it passes through the response from Bloom.
I think this way is better vs just calling Bloom directly from the frontend because:
1) it allows us to prop a cache
2) its consistent with listings/includeExternal
3) it allows us to manipulate the response with Doorway data if we ever need to (e.g. if BAHFA wants to blocklist listings).
Update your …
=> Feat: Add new /listings/bloom/:id endpoint

backend/core/src/seeder/seeds/listings/listing-default-sanjose-seed.ts, backend/core/src/seeder/seeds/listings/listing-triton-seed.ts, backend/core/src/seeder/seeds/listings/shared.ts, backend/core/test/activity-logs/activity-log.e2e-spec.ts, backend/core/test/ami-charts/ami-charts.e2e-spec.ts, backend/core/test/applications/applications.e2e-spec.ts, backend/core/test/authz/authz.e2e-spec.ts, backend/core/test/listings/listings.e2e-spec.ts, backend/core/test/user/user.e2e-spec.ts
Fixes the integration tests that I broken in #15. Unit tests are still green.
Now:
=> Re-green the e2e test suite

backend/core/src/listings/dto/doorway-listings-external-query-params.ts, backend/core/src/listings/listings.controller.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts, backend/core/test/listings/listings.e2e-spec.ts, backend/core/types/src/backend-swagger.ts
cc @phattya @ifranch @glgh  (cc-ed to read, but not reviewers per chatroom thread)
Continues work on #11 .
This test adds the /includeExternal endpoint and has backend changes only. The frontend will use this in another followup PR.
see above
* wrote tests
* tested by running a demo (see screenshot above)
* 
- Either explicitly ask a clarifying question, request …
=> Add /listings/includeExternal endpoint

backend/core/.env.template, sites/public/.env.template, sites/public/next.config.js, sites/public/src/lib/helpers.tsx, sites/public/src/lib/hooks.ts, sites/public/src/pages/listings.tsx
[[note this is a copy of #29 which I will close]]
cc @glgh @phattya @ifranch @
This PR continues work on #11 by updating the public site /listings page to call the endpoint introduced in #26.
Note that bc #26 is not yet merged in, there are overlapping changes. when #26 goes in the diff will be cleaner, in the meantime please just look at `sites/public` changes. I considered opening a PR to merge into the branch in #26 but I think scales better since otherwise I'd have to close this PR and reopen another one if/when that merges in, and the tests only run on PRs against `main`.
pull the branch, update env files, and observe that you can see external listings
- Review the code itself from a style …
=> feat: change public site to query for external listings (redux)

.github/workflows/unit_tests_shared_services.yml
This PR addresses #20 
Add unit tests for new shared-services package to Github Actions so they are automatically run on every PR.
Tested the yarn test:shared:services command.
=> feat: automate shared services tests

sites/public/src/components/listing/ListingGoogleMap.tsx, sites/public/src/components/listing/ListingMap.tsx, sites/public/src/components/listing/ListingView.tsx
This PR addresses #70 and #71
- Replace the Mapbox map on the individual listing page with a Google Map using the Google Maps Javascript API. The map has a marker with the listing location.
- Open Google Maps in a new tab when the map is clicked on. The href link is the same as the existing one for "View on Map" at the top of the listing page, and uses the address as the search instead of the coordinates.
- Add a Google Maps API key to the .env file for the public site.
- Bring up the public site and check the individual listings page.
- Also review the acceptance …
=> feat: add dynamic google map on individual listings page

backend/core/src/listings/listings.service.ts, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
This PR addresses #76 
These changes are in the 
- Remove the question asking whether a new listing uses the common digital application, which comes after the question about whether there is a digital application. The new flow is: if there is a digital application, show the (existing) question about whether there is a custom URL to use.
- Mark the custom URL question as required when it's displayed, by adding a subnote.
- Add a comment saying the common digital application question should be added back in when new applications can be submitted from Doorway.
See UI specifications [here](https://docs.google.com/presentation/d/1Znd2ZS6QWkBvVM-ypaGZKKl6YYT1t0-_vf_QFQR_ZmQ/edit#slide=id.g22dd6eefa2b_0_0).
- Bring up the partners portal.
- Log in to the partners portal
- Click on "add listing" …
=> feat: remove common digital application option from the partners site for new listings

build/docker/Dockerfile.backend
This PR addresses #59 
The docker images generated for the backend service lack some dependencies for executing `yarn db:*` commands, such as the postgres client.  This PR adds these dependencies into a separate build stage named "migrate" that builds upon the "run" target.  This will keep the runtime image small, improving build and startup times, and will keep each image focused on a single task in accordance with best practices.
From the repo root, build the image: 
`docker build --file build/docker/Dockerfile.backend --target migrate -t doorway/backend:migrate ./backend/core`
Then reseed your database with the generated image (below assumes default user/password/etc):
`docker run --env-file backend/core/.env -e PGUSER=bloom-dev -e PGPASSWORD=bloom -e PGHOST=localhost -e …
=> fix: add migrate stage to backend docker

sites/public/src/lib/helpers.tsx
This PR addresses #73 
Prepend index number (starting from 1) to the listing name in the list of results in the listings page. The numbers match the indices used in the map pins since both components get the same already sorted listings and don't do any additional sorting.
Bring up the public site and go to the listings page. Verify that the listings have indices in order starting from 1, and that those match the indices displayed on the map pins.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …
=> feat: add number to listing results

sites/public/src/components/listing/GetApplication.tsx, sites/public/src/components/listing/ListingView.tsx, sites/public/src/pages/listing/[id]/[slug].tsx, sites/public/src/pages/listing/ext/[id].tsx, sites/public/src/pages/preview/listings/[id].tsx
This PR addresses #92 
- For external listings, find the jurisdiction's URL and prepend it to the application process site URL to link to the application process page on Bloom sites
- Open the application link in a new tab for both 3rd party URLs and Bloom (external) listings that use the common digital application
You'll first need to seed external listings. Follow these steps:
- Go to `./tasks/import-listings`
- Run `yarn install`
- Run `yarn build`
- Run `DATABASE_URL=postgres://bloom-dev:bloom@localhost:5432/bloom EXTERNAL_API_BASE=https://proxy.housingbayarea.org JURISDICTION_INCLUDE_LIST="San Jose,San Mateo,Alameda" yarn import:run`. If you have a different username or password than bloom-dev and bloom, replace those
- Update the environment variables (BLOOM_API_BASE) for …
=> Link bloom application process page from individual listings page for external listings

tasks/import-listings/src/etl/transform/map.ts, tasks/import-listings/src/etl/transform/transformer.ts, tasks/import-listings/src/types/listing.ts, tasks/import-listings/test/etl/transformer.spec.ts
This PR addresses #102
This PR modifies the transformer function for `buildingAddress` to assign a county to the address does not already exist according to the business logic laid out in the [Doorway jurisdiction design doc](https://docs.google.com/document/d/1kyVX9cJUTa3XcUBWKkudeE8X2BgpvCZs6ww07NaM4bc/edit#heading=h.5ku3nid3w6da).
Unit tests have been added, so just run `yarn test`. …
=> feat: set county on building address

tasks/import-listings/.env.template, tasks/import-listings/index.ts, tasks/import-listings/src/etl/extract/extractor.ts, tasks/import-listings/src/etl/transform/map.ts, tasks/import-listings/test/etl/transformer.spec.ts
This PR updates the listings import task to include derived values for filter fields added in #110.  It also adds a new env var, `LISTING_VIEW`, to provide control over what data is pulled in.  This is mainly just a temporary fix to address the fact that some unit fields that are needed for filtering are missing on the base view.
You will need to have a copy of the database from PR #110 in order for the import to work, but if you do, you can run `yarn import:run` as normal then check the values in the `external_listings` table or `combined_listings` view.
Otherwise, `yarn test` works fine for verifying that things work as expected.
- Pull the …
=> Add filter data to external listings in listing import

tasks/import-listings/.env.template, tasks/import-listings/README.md
This PR adds a minimal README to the listings import task that documents env vars and provides an example import command.  Future updates targeted after code freeze will expand upon this to add more info and additional commands.
Docs only, no testing required
If you have one …
=> docs: add etl readme

backend/core/package.json, build/docker/Dockerfile.backend, ci/buildspec_backend.yml, ci/buildspec_deploy.yml, ci/buildspec_partners.yml, ci/buildspec_public.yml
This PR addresses https://github.com/metrotranscom/doorway/issues/88
The dev infra is running `yarn db:reseed` but it's not connecting to the database correctly.
If you have one commit and message, squash. If you need each message to be …
=> ci: fix db reseed on dev infra

doorway-ui-components/src/actions/ButtonGroup.scss, doorway-ui-components/src/actions/ButtonGroup.stories.tsx, doorway-ui-components/src/actions/ButtonGroup.tsx, sites/public/src/components/listings/ListingsCombined.tsx, sites/public/src/components/listings/ListingsList.tsx, sites/public/src/components/listings/Pagination.tsx, sites/public/src/components/listings/search/ListingsSearchCombined.tsx, sites/public/src/components/listings/search/ListingsSearchModal.tsx, sites/public/src/lib/listings/listing-service.ts, sites/public/src/pages/listings.tsx
This PR adds pagination to the bottom of the listings page and updates the search to only pull 10 listings at a time rather than all of them.  The components are from `doorway-ui-components`/`ui-components` as appropriate.  It also modifies the info cards to only show on the last page of results.
First page:
Middle page:
Last page:
Start up the public site as usual and navigate to `/search-demo`.  Search for some listings (broader search is better).  Note that there are only 10 listings returned and that there are buttons at the bottom that let you move through the pages of listings.  Scroll through the listings by clicking either the forward/backward arrows or by clicking on a specific page.  Note also that the info cards only show on the last page.
Note that the …
=> feat: add pagination to listings

sites/public/src/components/listings/ListingsList.tsx
Adds the URL to the GovDelivery topic sign-up
Click on the link to `SIGN UP` on the `Sign up for listing alerts` card at the end of the ListingsList and a new tab should open https://public.govdelivery.com/accounts/CAMTC/signup/36832.
If you have one …
=> Update link for listing email notifications to GovDelivery

backend/core/package.json, build/docker/Dockerfile.backend
The release PR that was merged in recently (#131) introduced a change that broke the build process for the backend docker file.  This PR updates the dockerfile to correct the issue and moves a couple of necessary runtime dependencies from `devDependencies` to `dependencies` in the package.json file.
From the repo root:
**Run unit tests**
`docker build --file build/docker/Dockerfile.backend --target test -t doorway/backend:test .`
`docker run --env-file backend/core/.env --network host doorway/backend:test`
**Run the service**
`docker build --file build/docker/Dockerfile.backend --target run -t doorway/backend:run .`
`docker run --env-file backend/core/.env --network host doorway/backend:run`
**Run the migration**
`docker build --file build/docker/Dockerfile.backend --target migrate -t …
=> fix: update backend docker

sites/public/src/pages/listing/ext/[id].tsx
The merging of PR #131 introduced an uncaught error in the public site under the `listings/ext/[id].tsx` page. This PR changed the return value for the function used to get the image URL for a listing from a single string value to an array of strings.  A longer-term fix may be to implement both versions of this function (`imageUrlFromListing` implies a single value and should be more accurately named `imageUrlsFromListing` anyway), but this PR implements a simple fix that unblocks the building of the public site.
Before this fix, running `yarn build` under `sites/public` would fail.  It should pass now.
- Pull the changes down locally and test …
=> fix: update listings/ext for multi images

ci/buildspec_backend.yml
A recent merge broke the build pipeline for the backend service.   The root cause was addressed in a previous PR, but the pipeline itself was not updated.  This PR updates the buildspec file for the backend service to complete the fix.
This is a minor change with very complex testing requirements.  Visual verification is recommended, but additional testing details can be provided if comprehensive testing is required.
- Either …
=> fix: change build dir for backend buildspec

backend/core/src/app.module.ts
The `backend/core` service accepts multiple values for the `CORS_ORIGINS` env var, but there isn't a way to define an array with normal environment variables, which is what is used in a non-local runtime like our AWS environments.  This PR adds the option to define a comma-delimited list of origins that can be passed in as a string from the runtime environment and turned into an array of values during startup.
Set `CORS_ORIGINS` in your `.env` file to `CORS_ORIGINS=http://localhost:3000,http://localhost:3001`, then run `yarn build` and `yarn start`.  You should see a line in the startup output that looks something like this:
CORS only comes into play when making client-side requests.  Most requests to the backend come from the server-side instead, but the search page on the public site …
=> feat: enable csv for cors origins

sites/public/src/pages/listings.tsx
A previous PR included a merge with with changes that used a function that had been deprecated/removed, causing the public site to not build.  This wasn't caught by the checks, so the merge went through with broken code.  This addresses the issue with two small changes.
The changes are minor, but if you run `yarn build` in `sites/public`, it should build without error.
- Either explicitly ask a clarifying question, request …
=> fix: update function call to get listings url

sites/public/src/components/listings/search/ListingsSearchCombined.tsx, sites/public/src/pages/listings.tsx
BAHFA requested a larger page count, so changing to 25. Also updating the filter default to be all counties, since none of our seed data is from the 3 counties that were checked, and it's easier for the user to start with all data shown.
Recommend seeding with
To test `yarn dev` on public & backend core (or `yarn dev:all` if that's the way you like to do it) and check the filter defaults are set as shown here:
and check that the page count covers 25 per page ... if you used `yarn db:reseed:with-external:dev` you will see the following
- Review the …
=> Change Public site page size to 25 and add all counties selected as filter default 

ci/buildspec_copy_image.yml
This PR adds a buildspec file that copies an image from one repo into another.  This will enable us to move validated images from one stage to another (ie dev->staging->prod) without having to rebuild them.
This is the  command I used to test locally: `codebuild_build.sh -i public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0 -a cb_out -b buildspec_copy_image.yml -e ../.copy-images.env -c`
The `.copy-images.env` file looked like this:
```
ECR_ACCOUNT_ID=364076391763
ECR_REGION=us-west-1
SOURCE_REPO_NAMESPACE=doorway-dev
DEST_REPO_NAMESPACE=doorway-chriscasto
SOURCE_IMAGE=backend:run
DEST_IMAGE=backend:copy-test
```
I was able to verify that the checksum for the image copied over from the dev environment matches the one for the image uploaded to my personal environment.
Steps to …
=> feat: add copy image buildspec

doorway-ui-components/index.ts, doorway-ui-components/src/actions/DoorwayCollapsibleSection.scss, doorway-ui-components/src/actions/DoorwayCollapsibleSection.stories.tsx, doorway-ui-components/src/actions/DoorwayCollapsibleSection.tsx
This CL adds a new UI component that is used extensively in the help center. 
https://github.com/metrotranscom/doorway/assets/10789523/70a362d8-4191-4b4e-a9b9-2d0ffc31cddc
=> feat: add new collapsible section component

sites/public/src/components/listing/ListingView.tsx
Add the url param to the external apply link
=> [easy] feat: add url param

backend/core/src/assets/assets.controller.ts, backend/core/src/assets/entities/asset.entity.ts, backend/core/src/assets/services/assets.service.ts, backend/core/test/assets/assets.e2e-spec.ts, backend/core/types/src/backend-swagger.ts, sites/partners/.env.template, sites/partners/__tests__/components/listings/PaperListingForm/sections/LotteryResults.test.tsx, sites/partners/next.config.js, sites/partners/package.json, sites/partners/src/components/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailListingPhoto.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx, sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx, sites/partners/src/lib/assets.ts, sites/partners/src/lib/helpers.ts, sites/partners/src/pages/_app.tsx, sites/partners/src/pages/api/adapter/upload.ts
This PR addresses the issue of uploads not working
The ability to upload files to S3 was only partially implemented due to some unexpected behavior on the Bloom side that made it impossible to complete via the previous direction.  This adds on to previous PRs to complete the work of implementing file uploads via the backend.
Both the backend and the partner site will need to be rebuilt and started up.  You will also need to have local AWS credentials for the uploads to actually go into S3.  For the backend site, update your `.env` with these values:
```
ASSET_FILE_SERVICE=s3
ASSET_FS_CONFIG_s3_REGION=us-west-1
ASSET_FS_CONFIG_s3_BUCKET=doorway-chriscasto-public-uploads20230601213649025400000006
ASSET_FS_CONFIG_s3_URL_FORMAT=public
```
Once both are running, log into the partner site. …
=> feat: update partner uploads

doorway-ui-components/src/headers/SiteHeader.scss
=> chore: update z index of menu

doorway-ui-components/src/actions/ButtonGroup.scss, doorway-ui-components/src/actions/ButtonGroup.tsx, doorway-ui-components/src/forms/Field.scss, doorway-ui-components/src/forms/Field.tsx, doorway-ui-components/src/global/forms.scss, doorway-ui-components/src/global/mixins.scss, doorway-ui-components/src/overlays/Modal.scss, doorway-ui-components/src/overlays/Modal.tsx, sites/public/public/images/check-black.svg, sites/public/src/components/listings/ListingsCombined.tsx, sites/public/src/components/listings/search/ListingsSearchCombined.tsx, sites/public/src/components/listings/search/ListingsSearchModal.tsx
This PR addresses restyle search modal work
Figma …
=> chore: restyle listings search modal

shared-helpers/__tests__/pdfs.test.ts, shared-helpers/__tests__/photos.test.ts, shared-helpers/src/utilities/pdfs.ts, shared-helpers/src/utilities/photos.ts
This PR addresses: external listings are not able to be resolved, due to a missing asset.label. This returns the Cloudinary path by default. 
- Also review the acceptance criteria on the Netlify deploy preview (noting that these …
=> fix: external listings have wrong asset.label

doorway-ui-components/src/headers/DoorwayHero.scss
https://github.com/metrotranscom/doorway/assets/10789523/274aff23-f5af-46d7-ba48-2dff2942d6d2
=> Hide Doorway hero photo between medium and large screen sizes

doorway-ui-components/src/config/NavigationContext.tsx, sites/public/src/pages/_app.tsx
This PR fixes the bug where when you click on a link after changing the language, the language choice does not persist.
It took awhile to figure out, but then I realized it's bc we don't pass the Next link through the Doorway UIC navigation provider (but do for regular UIC).
https://github.com/metrotranscom/doorway/assets/10789523/5f69a7b3-b364-4d87-8e42-830f34483c0c
=> Feat fix translations

sites/public/src/components/listings/ListingsList.tsx
This PR addresses show end-of-listing cards when zero listings are returned from the query. 
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the …
=> fix: listings cards on empty results

backend/core/src/email/email.service.spec.ts, backend/core/src/shared/views/partials/header.hbs
Update the email template to the Doorway logo sizes plus padding.
Adjusting the logo dimensions.
Here's what it did look like: 
And here's what it will look like: 
If you have one commit and message, squash. If you need each message to be applied, …
=> change logo dimensions & add padding & spacing

build/docker/Dockerfile.sites-generic, ci/buildspec/build_partners.yml, ci/buildspec/build_public.yml
The env var for the MapBox token was missing from the build step for the frontend sites.  This adds them.
Build a public and/or partner site docker container using the command in the buildspec file, or run the command below if you have the local CodeBuild agent installed.
`codebuild_build.sh -i public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0 -a cb_out -b ci/buildspec/build_public.yml -e sites/public/.env -c`
- Either …
=> feat: add mapbox vars to build steps

sites/partners/src/pages/listings/[id]/index.tsx
This PR addresses `Partners a specific Listing's Edit & Preview buttons are sometimes showing up at the bottom of the page.`
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include …
=> fix: ensure edit/preview buttons at top right of content

doorway-ui-components/src/overlays/Modal.scss
This PR addresses on mobile: increase margin-bottom on search modal
- Either explicitly …
=> fix: increase mobile search modal margin-bottom

sites/public/src/components/listings/ListingsCombined.tsx, sites/public/src/components/listings/ListingsList.tsx, sites/public/src/components/listings/search/ListingsSearchCombined.tsx
this was driving me crazy
https://github.com/bloom-housing/bloom/assets/10789523/140acf91-6af5-456c-9d9c-7a472cfd7df2
https://github.com/metrotranscom/doorway/assets/10789523/2de75665-dc55-4e55-8f7d-3b7ef16570cf
=> feat: add loading spinner

build/docker/Dockerfile.sites-generic, ci/buildspec/build_public.yml
The GTM_KEY var needs to be passed in to the build process so Next.js can bake it into the binary.  This adds that key to the public buildspec and Dockerfile.
Run the buildspec locally or update a personal development pipeline to build the public site with this branch.
If you …
=> feat: add gtm var to public buildspec and dockerfile

doorway-ui-components/src/config/NavigationContext.tsx, doorway-ui-components/src/page_components/listing/ListingCard.tsx
This PR addresses linkref console error when loading `/listings`
- Either explicitly ask …
=> fix: linkRef console error

sites/public/src/components/listings/ListingsCombined.tsx, sites/public/src/components/listings/ListingsList.tsx, sites/public/src/components/listings/search/ListingsSearchCombined.tsx, sites/public/src/components/listings/search/ListingsSearchModal.tsx
This PR addresses a bug introduced https://github.com/metrotranscom/doorway/pull/213/files . The landing page results are lost and the query results are returned with no filters. 
- Also review the acceptance criteria on the …
=> REVERT: fixing bug that causes re-rendering landing page results

sites/public/src/components/listings/ListingsList.tsx
this button is a no-op so just hide it
=> feat: hide no-op clear filter button

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, sites/public/src/pages/index.tsx
This PR addresses [#3541](https://github.com/bloom-housing/bloom/issues/3541)
This PR updates the welcome banner according to the contents of the issue. 
This can be tested by pulling the PR down locally and ensuring that the string "We're just getting started and will be adding more listings soon!" has been added to the banner. Then ensure it is present in each of the available languages. …
=> fix: english content updates

doorway-ui-components/src/global/forms.scss, doorway-ui-components/src/headers/DoorwayHero.scss, sites/public/src/components/listing/ListingView.tsx, sites/public/src/components/listing/SubmitApplication.tsx, sites/public/src/components/listings/search/LandingSearch.tsx, sites/public/src/pages/index.tsx
This PR addresses #264
This PR includes color updates based on the Exygy recs section of [this sheet](https://docs.google.com/spreadsheets/d/15fiMtSNTMZPghrszS7uw4CEk7F4_8HrK4uQsTN3btEQ/edit#gid=0) (under Source: Accessibility Errors).
This can be tested by pulling this down locally, reseeding, and then using two approaches:
1) utilizing an a11y extension such as the [WAVE web accessibility tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) which when run should show no contrast errors on the homepage or when looking at Test: Coliseum detail page.
2) Using inspect element to check if the colors now reflect the exygy recs described in the sheet
Currently exploring ways to better test ID-8 on the sheet locally but for now, here is a screen …
=> fix: updated color contrasts

backend/core/src/listings/combined/README.md, tasks/import-listings/README.md
This PR adds documentation for the listings import task and the combined listings code in the backend.
This is a documentation-only change.
=> docs: add combined listings readme

doorway-ui-components/src/actions/DoorwayCollapsibleSection.tsx, yarn.lock
This PR addresses [#10](https://github.com/bloom-housing/Bloom-Doorway/issues/10)
These changes correct the alignment on the help center questions. 
Also, this includes some yarn.lock changes that were missed on main.
This can be tested by pulling this down locally and going to http://localhost:3000/help/questions
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining …
=> fix: align questions to left

doorway-ui-components/src/headers/SiteHeader.tsx, sites/public/src/lib/helpers.tsx
This PR addresses [#11](https://github.com/bloom-housing/Bloom-Doorway/issues/11)
This is a small bug fix where the Help Center navigation item was not highlighting as the active color when any of its dropdown items were selected.
Ensure if you navigation to the Help Center pages, that while those pages are active, the navigation item title appears in a highlighted primary color state. …
=> fix: highlight help center nav item when selected

doorway-ui-components/src/footers/SiteFooter.scss, doorway-ui-components/src/footers/SiteFooter.tsx, doorway-ui-components/src/navigation/FooterNav.scss, doorway-ui-components/src/navigation/FooterNav.tsx, doorway-ui-components/src/sections/FooterSection.scss, doorway-ui-components/src/sections/FooterSection.tsx, sites/partners/__tests__/pages/listings/index.test.tsx, sites/partners/__tests__/pages/users/index.test.tsx, sites/partners/src/layouts/index.tsx
This PR addresses [#19](https://github.com/bloom-housing/Bloom-Doorway/issues/19)
The footer in the partners portal was misaligned (screenshot in the ticket).
The issue here was that when a local version of the footer component was created for use on the public site and the styles were changed, these same Doorway UIC styles were being applied on the partners site even though the partners site was using the UIC footer because the class names were the same. I just prepended the doorway version with `doorway`.
Ensure that the partners portal footer matches [Bloom core dev](https://partners.bloom.exygy.dev/sign-in).
- Pull the changes down locally …
=> fix: partners portal misaligned footer

backend/core/src/migration/1692890494691-ami-120-updates.ts
This PR addresses #311 
This PR adds the highlighted rows in the sheet [here](https://docs.google.com/spreadsheets/d/1FIYA_u0P0PkxWN1Ztg-ipzEjmjGTAVRo4Yjr9tastOo/edit#gid=0)
It's difficult to test out in dev since the current chart names that I'm adding the 120% data to aren't in the seeded data but it will be helpful to see it in staging first. Anything I'm missing?
- Either explicitly ask a clarifying question, request …
=> fix: add 120% ami info

doorway-ui-components/src/headers/DoorwayHero.scss, sites/public/src/components/listings/search/LandingSearch.module.scss, sites/public/src/components/listings/search/LandingSearch.tsx
This PR addresses https://github.com/bloom-housing/Bloom-Doorway/issues/17
Updates the homepage layout to more closely match the image in the issue.
Review the homepage at mobile, tablet, and desktop layouts and ensure things stay nicely aligned and at desktop matching the Figma screenshot. There's a bit less left hand padding between the image and the form fields to accommodate having the num bedrooms all being on one line.
- …
=> fix: homepage layout alignment

sites/public/src/components/listings/ListingsCombined.tsx, sites/public/src/components/listings/search/ListingsSearchCombined.tsx
This PR addresses #297
This PR adds scroll reset on pagination, both for scrollable listings container, and whole window. In task it was specified only for pagination, but as it's implemented by same function then it makes sense to keep it also for search (fliters), as it also seem to be expected for this case.
Different div's are responsible for scroll for different views (mobile / desktop) so i just scroll them all top, to not overcomplicate.
If you have more that 25 listings just go to `/listings` on public and test if it returns to top on page change / filtering.
If not then you can change page size in `ListingSearchCombined.tsx` line 66
Check also on mobile view + mobile view with expanded listings list
- Read and understand the issue, and ensure the author has …
=> fix: scroll to top on search / pagination

build/docker/Dockerfile.backend
This adds the scripts folder to the backend docker file
=> Docker file updates

doorway-ui-components/src/notifications/ApplicationStatus.tsx
This PR addresses [#3630](https://github.com/bloom-housing/bloom/issues/3630)
It pulls [this](https://github.com/bloom-housing/ui-components/pull/122) change from ui-c. 
Instructions in mentioned PR
If you have one commit and message, squash. If you need each message to be …
=> fix: hide application status when no content to display

build/docker/Dockerfile.sites-generic
Adds the listings approval flag to the docker file
=> fix: add listings approval variable to docker file

ci/buildspec/build_partners.yml
=> fix: add la feature flag to global

.github/workflows/cypress_partners.yml, .github/workflows/cypress_partners_la.yml, sites/partners/cypress.config.ts, sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts, sites/partners/cypress/fixtures/jurisdictionalAdminUser.json, sites/partners/cypress/fixtures/minimalListing.json
This PR addresses #327
Adds a new Cypress job for the listings approval Cypress tests.
Check out the job below!
=> test: add new workflow for LA cypress tests

sites/public/src/lib/helpers.tsx
This PR addresses #374 
email changes in the footer
=> fix: update footer email

backend/core/src/migration/1697654611220-turn-on-listing-approval.ts
This PR addresses #298 
This PR adds a migration to add "admin" to the listing approval permissions array. The plan is to release this change on October 25th (wed)
It is recommended that you reseed before you pull down this change and then run the migrations. That way it will simulate the real flow.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR …
=> fix: add migration to add listing approval permissions

sites/public/styles/overrides.scss
This PR addresses #48
With the recent uptake of ui-c there are competing overrides of some variables. This removes the smaller value and it takes the `75px` value from the other override file.
In Prod:
With this change
- Either explicitly ask a clarifying question, …
=> fix: remove siteheader dropdown override

backend/core/src/email/email.module.ts, backend/core/src/email/email.service.spec.ts, backend/core/src/email/email.service.ts, backend/core/src/jurisdictions/entities/jurisdiction.entity.ts, backend/core/src/listings/listings.service.ts, backend/core/src/migration/1699380281858-listing-opportunity.ts, backend/core/src/seeder/seeds/jurisdictions.ts, backend/core/src/shared/views/listing-opportunity.hbs, backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts, backend/core/test/listings/listings.e2e-spec.ts
This PR addresses #368 
This connects the listing update call to the govDelivery automated email. It also calculates the dynamic information from the listing in order to populate the table information. 
Lastly it wraps the code in a new feature flag tied to the jurisdiction. The migration script adds the new feature flags and translations, but does not turn on the feature.
In order to test this with the govDelivery stage environment you can reach out to @ludtkemorgan to get yourself added to the email subscribe list.
You will also need the following variables setup in your backend .env file. You can get the values for those from @ludtkemorgan as well
```
GOVDELIVERY_USERNAME=
GOVDELIVERY_PASSWORD=
GOVDELIVERY_API_URL=
GOVDELIVERY_TOPIC=
```
The feature flag will also need to be turned on …
=> fix: calculate fields for auto email

backend/core/src/email/email.service.ts, backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts
This PR addresses #368 
This is a bug fix for the automated email feature. The "name" of the community type doesn't exist on the listing object because all we know about it is the "id". This change is to fetch the rest of the community type info before sending the email
Same steps to test the automated email as listed here: https://github.com/metrotranscom/doorway/pull/408. Make sure a reserved community type is set on this listing to be published
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend …
=> fix: get the correct community type for auto email

sites/public/tailwind.config.js
This PR addresses #422 
This is a follow-up which supports tailwind loading from the Account Card in shared helpers.
This can be tested by running yarn build / yarn start in sites/public and the sign-in page styling should show as expected. Specifically, there should be margin around the create account header and buttons on the sign-in page
- Either explicitly ask a clarifying question, request changes, or approve the PR if …
=> fix: shared-helpers tailwind config

doorway-ui-components/src/headers/SiteHeader.tsx, shared-helpers/src/auth/UseRequireLoggedInUser.ts, shared-helpers/src/views/accounts/AccountCard.module.scss, shared-helpers/src/views/accounts/AccountCard.tsx, shared-helpers/src/views/forgot-password/FormForgotPassword.tsx, shared-helpers/src/views/sign-in/FormSignIn.tsx, shared-helpers/src/views/sign-in/FormSignInErrorBox.tsx, sites/public/src/components/account/ConfirmationModal.tsx, sites/public/src/components/account/SignUpBenefits.tsx, sites/public/src/components/account/SignUpBenefitsHeadingGroup.tsx, sites/public/src/components/account/StatusItem.tsx, sites/public/src/components/applications/SubmittedApplicationView.tsx, sites/public/src/layouts/application.tsx, sites/public/src/lib/helpers.tsx, sites/public/styles/sign-up-benefits.module.scss
- Style Tweaks
- Router push fix
Functional Testing:
As a signed out user, do the following:
- Go to a listing, click apply online, create an account, go to email, click link, and then you should be redirected to application
- Do the same, but this time hit the 'Resend Confirmation" button in the modal, should work
- Then if you create an account, hit resend confirmation, and then click on the FIRST email, you should see a timeout modal, which is currently not working on full. I created a bug ticket here: https://github.com/bloom-housing/bloom/issues/3846
- Sign Out, Go to a listing, click apply online, login, redirect to application
- Sign Out, Go to a listing, click apply online, forget password, email, click link, redirect
- Toggle the feature toggle off and …
=> feat: mandated accounts followup

backend/core/src/applications/services/application-csv-exporter.service.ts, shared-helpers/src/locales/general.json, sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx, sites/partners/src/lib/applications/formatApplicationData.ts, sites/public/src/pages/applications/review/demographics.tsx, sites/public/src/pages/applications/review/terms.tsx
This PR addresses #480 
This PR allows the "Not Listed" option for the Spoken Language demographic to ask a followup "Please Specify" text field. It's stored in the database as "notListed:User input here" similarly to the race demographic "other" options.
Choose "Not Listed" for Spoken Language and fill in a custom language.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small …
=> feat: add Please Specify text field for Spoken Language

sites/public/src/pages/listing/ext/[id].tsx, tasks/import-listings/src/etl/transform/map.ts
This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3779)
This modifies the import job mapper so that it correctly maps in the new changes introduced by prisma to the existing typeorm format
The easiest way to test this is to aim the import + reseed job at the core heroku instance ala: 
`"import:run:local:dev": "EXTERNAL_API_BASE=https://bloom-backend-main.herokuapp.com LISTING_VIEW=full yarn import:run:local",` 
then run `yarn db:reseed:with-external:dev` 
from there you can check to the front end to make sure the data is importing properly and/or check the external_listings table in the db
- Pull the changes down locally …
=> feat: modifications for upcoming prisma

backend/core/src/auth/services/user.service.ts
We do not currently expose this endpoint from the UI, but we are still vulnerable because this endpoint does exist on the API. This pulls the change from HBA over to Doorway
- [] I have made corresponding changes to the documentation
If you have one …
=> fix: limit the characters for user names

api/prisma/migrations/03_1_combined_listing/migration.sql, api/prisma/migrations/05_single_use_code_translation_updates/migration.sql, api/prisma/schema.prisma, api/src/services/listing.service.ts, sites/public/src/pages/404.tsx, sites/public/src/pages/_error.tsx
This PR addresses: Bugs found in bashing
This PR addresses the following bugs:
1. 404 page sends you to the wrong "additional resources" page (also an issue in prod currently)
2. external listing details page not routing correctly
3. MFA code email has incorrect translation
4. Partner site some listing editing page not working correctly. 
This PR does not address the following:
- Studio filter not working.
- This issue is also in prod so not a release blocker, but still investigating why it is an issue
Pull down and do:
`yarn prisma generate`
`yarn db:reseed:with-external:dev`
Then start up normally.
- Pull the changes down locally and test …
=> fix: bug bash fixes

api/prisma/migrations/03_1_combined_listing/migration.sql, api/prisma/schema.prisma, build/docker/Dockerfile.backend, sites/public/src/components/listing/ListingView.tsx
This PR addresses: issues found during bash
This addresses the following bugs found:
- Unable to download CSV in deployed AWS environment
- The docker build file was not giving the temp directory full access
- Links to external applications was not working
- The "public" url is still only coming back from the old field and will require a change to HBA to fix. So adding backward compatibility in the meantime
- mandated accounts is forcing people to login even for external listings so changed that 
You should be able to go to an application for an external listing on the listing details page.
Testing the docker image is a bit more complicated. I will update the readme on how to do that at some point
- Read and understand the issue, and ensure the author has added QA …
=> fix: bug bash fixes 2

sites/public/src/pages/preview/listings/[id].tsx
The Listing Preview page isn't working because of an error when getting the jurisdiction. The new backend returns "jurisdictions" instead of "jurisdiction". 
On the partner site go to any listing and click the "preview" button. It should bring you to the public listings page with the preview banner
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is …
=> fix: listing preview page fix

sites/partners/__tests__/components/listings/ListingFormActions.test.tsx, sites/partners/src/components/listings/ListingFormActions.tsx
This PR addresses #516
This temporarily removes the button to post lottery results for closed listings.
Look at a closed listing and ensure there's no button on the sidebar.
=> chore: temporarily remove Post Results button in Partners

api/prisma/seed-dev.ts, api/prisma/seed-staging.ts, api/src/controllers/user.controller.ts, doorway-ui-components/src/global/tokens/colors.scss, doorway-ui-components/src/notifications/AlertBox.scss, shared-helpers/src/views/sign-in/FormSignIn.module.scss, sites/public/.env.template, sites/public/next.config.js, sites/public/styles/overrides.scss
=> fix: release fixes

shared-helpers/package.json, sites/partners/package.json, yarn.lock
Ensure that BloomCard overrides are coming through by checking out any of the cards, like the sign in page or the create account page.
Before:
After:
=> fix: card fixes

sites/public/src/pages/applications/contact/address.tsx
This PR addresses #3973 as a 🍒 ⛏️ 
In the prisma changeover, the applicant.workAddress value was changed to applicant.applicantWorkAddress but the field names and associated errors in address.tsx had not been updated so the address wasn't being saved correctly.
Apply to a listing, indicate "yes" to the work in county, fill out the work address, complete the application, see the work address on the application summary page, submit, see that the work address successfully saved on the partner's side.
- Also review the acceptance criteria on the Netlify deploy preview …
=> fix: update naming to applicantWorkAddress (#3975)

api/src/services/listing.service.ts
we are occasionally getting errors where if we have a numeric filter come in as floating point the query breaks
this enforces an integer by taking the floor of the value
I haven't been able to consistently raise the error but this fix should cover you entering decimals into those fields
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise …
=> fix: number filter fix

shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/locales/tl.json, shared-helpers/src/locales/vi.json, shared-helpers/src/locales/zh.json, sites/partners/src/layouts/index.tsx, sites/public/src/layouts/application.tsx
This PR addresses #573 
This PR reinstates the public application banner and removes the partners banner. Note that this PR removes the partner's banner but doesn't remove the partners env variable since I imagine it will be useful to have in the future.
This can be tested by making the maintenance window env var on public to include the current time and seeing the old banner on public. …
=> fix: update alert banner

sites/public/src/components/listing/ListingView.tsx, sites/public/src/lib/applications/configInterfaces.ts, sites/public/src/lib/hooks.ts, sites/public/src/pages/applications/start/choose-language.tsx
This PR addresses #582 
This PR allows partners to view the listing application in preview mode and prevents the confusing log ins or redirects that the issue describes.
This can be tested by logging in to the partner's site, preview a draft listings application (open link in new window so that session doesn't carry over via local host), and ensure you access the application. Then go to an open listing on the public side to ensure that the MA account checks are still in place.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do …
=> fix: preview checks for  MA flow

api/src/services/application.service.ts
This PR addresses #4060 
Previously, the dto was being passed which doesn't include the confirmationCode. Passing the mappedApplication resolves this.
This can be tested by filling out an application with an email and ensuring the application confirmation email comes through correctly with a confirmation code.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes …
=> fix: pass mappedApplication (#4061)

sites/public/src/components/listing/ListingView.tsx
This PR addresses #594 
The isCustomApp check was undefined for paper apps resulting in the published application redirecting users to the sign in page falsely. This updates that conditional to see if it is specifically a commonApp or not (false or undefined).
Test a listing with different combos of online apps and paper apps in both the preview and published state. …
=> fix: isCommonApp approach

sites/public/src/components/listing/ListingView.tsx, sites/public/src/pages/account/applications.tsx
=> fix: external case

shared-helpers/src/auth/catchNetworkError.ts
This PR addresses #597 
This PR captures the 401 error that's thrown when a partner user attempts to sign in on the public side (with password).
This can be tested by making a partner user with mfa enabled. 
1. Sign in with that user on the partners side and ensure the mfa flow works as expected
2. On the public side sign in, select sign in with password, and then attempt to sign in with email and password of partner user. You should see an error message indicating that it is a partner user.
- Also review the acceptance criteria on the Netlify deploy preview (noting …
=> fix: network error updates

sites/partners/package.json, yarn.lock
Reverting a recent PR that upgraded this package as the tests are failing and the fix may be more complex.
=> fix: versioning issue

doorway-ui-components/package.json, shared-helpers/package.json, sites/partners/package.json, sites/public/package.json, yarn.lock
This PR addresses #601
Uptakes latest UIC which includes the following changes:
* https://github.com/bloom-housing/ui-components/pull/138 Modal footer buttons should be visible on mobile
* https://github.com/bloom-housing/ui-components/pull/141 Accessibility fix on the loading overlay
* https://github.com/bloom-housing/ui-components/pull/143 Accessibility fix on the modal
* https://github.com/bloom-housing/ui-components/pull/146 Header CSS issue
* https://github.com/bloom-housing/ui-components/pull/147 Make Subheader content more flexible
* https://github.com/bloom-housing/ui-components/pull/149 Remove tooltip text
^ This last commit in UIC is what resolves the tagged issue. There should no longer be tooltips on our input fields.
Start a new application and hover your text over the input …
=> fix: remove form field titles

api/.env.template, api/src/services/auth.service.ts
Currently our cookies are set strictly on sites so something like `example.our.domain` would work but `partners.example.our.domain` would not
This adds a domain env variable that should fix the issue
locally this is effectively impossible to test. Locally all requests come from localhost so there isn't anything to test here. I recommend reading up on: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent
and looking at the code though to understand what this pr is aiming to do
- Also review the acceptance …
=> fix: domain fix for doorway

api/package.json, api/src/logger/winston.logger.ts, api/src/main.ts, api/yarn.lock, sites/partners/package.json, sites/partners/src/logger.ts, sites/partners/src/pages/api/adapter/[...backendUrl].ts, sites/public/logger.ts, sites/public/package.json, sites/public/src/pages/api/adapter/[...backendUrl].ts, yarn.lock
This adds winston logging to the backend API and to all API calls on the public and partners portals. 
Cloudwatch logs should now be json formatted (and hopefully handled better)
If you have one commit and message, squash. If you need each message to be …
=> feat: adding winston logging to portals and api

build/docker/Dockerfile.sites-generic
- [ x] This change addresses the issue in full
I removed the default value from the site arg
There should be a real partners portal in the dev instance if i'm correct.
- [x ] My code follows the style guidelines of this project
- [x ] I have added QA notes to the issue with applicable URLs
- [x ] I have performed a self-review of my own code
- [NA ] I have reviewed the changes in a desktop view
- [ NA] I have reviewed the changes in a mobile view
- [ NA] I have commented my code, particularly in hard-to-understand areas
- [ NA] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ NA] I have added tests that prove my fix is effective or that my feature works
- [ NA] New and existing unit tests pass locally with my …
=> refactor: got rid of arg value in site arg

api/prisma/migrations/20240520173759_application_user_id_index/migration.sql, api/prisma/schema.prisma
This releases: https://github.com/bloom-housing/bloom/pull/4098 (new application index on user id)
=> feat: new application index on user_id (#4098)

api/prisma/seed-helpers/listing-factory.ts, api/prisma/seed-staging.ts, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx, sites/public/cypress.config.ts, sites/public/cypress/e2e/pages/submit-application.spec.ts, sites/public/cypress/mockData/applicationData.ts, sites/public/cypress/support/commands.js, sites/public/cypress/support/index.d.ts, sites/public/src/components/applications/ValidateAddress.tsx, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/household/member.tsx, sites/public/src/pages/applications/household/preferred-units.tsx
=> fix: saving household member (#4108)

shared-helpers/src/utilities/formKeys.ts, sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx, sites/public/src/pages/applications/review/demographics.tsx
fix: Demographics Race Field Render Issue (#4102)
Release https://github.com/bloom-housing/bloom/pull/4102
Flow 1: Go through public site online application flow
Flow 1a: Select a race, select a suboption of that race, select another race, unselect second selection, confirm original selections are still present.
Flow 1b: Make selections, click the Next button, click the Back button, confirm original selections are still present.
complete flow and submit.
Flow 2: Login to the partners side, navigate to an open listing, go to the Applications tab
Flow 2a: select Add Application, complete required fields, select a race, select a suboption of that race, select another race, unselect second selection, confirm original selections …
=> release: Demographics Race Field Render Issue

.github/workflows/unit_tests_api.yml, api/.env.template, api/prisma/migrations/11_add_script_runs/migration.sql, api/prisma/schema.prisma, api/src/controllers/auth.controller.ts, api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/data-transfer.dto.ts, api/src/modules/app.module.ts, api/src/modules/script-runner.module.ts, api/src/services/script-runner.service.ts, api/test/unit/services/app.service.spec.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This releases script runner for doorway
=> Release: script runner for doorway

docs/pull_request_template.md
Pulls over https://github.com/bloom-housing/bloom/pull/4116 from core
=> docs: release - updated pr template (#4116)

sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx, sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx, sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx, sites/partners/src/components/listings/PaperListingForm/index.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx, sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx, sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx, sites/partners/src/components/settings/PreferenceDrawer.tsx, sites/partners/src/pages/application/[id]/review.tsx
This PR includes the following Core PRs:
* https://github.com/bloom-housing/bloom/pull/4118
* https://github.com/bloom-housing/bloom/pull/4129
=> release: fix buttons and other elements from design QA

api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, sites/partners/src/components/listings/ListingFormActions.tsx, sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx, sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts, sites/partners/src/lib/listings/BooleansFormatter.ts, sites/partners/src/pages/listings/[id]/index.tsx, sites/public/__tests__/testUtils.tsx
* 2de28612c - fix: add error message for incorrect listing approval (#4134) 
* 0418793b6 - fix: allow removal of mailing address (#4130)
=> fix: allow removal of mailing address

sites/partners/src/pages/api/adapter/upload.ts
=> fix: one more backend dependency removed

sites/partners/package.json
Another dependency was found to not be in the public package
=> fix: add babel dependency

api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/ami-chart-import.dto.ts, api/src/modules/script-runner.module.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
this releases https://github.com/bloom-housing/bloom/pull/4125 to doorway (ami chart import script runner script)
=> feat: ami chart import script runner (#4125)

api/src/services/user.service.ts, api/test/unit/services/user.service.spec.ts
This PR addresses #656 
This PR updates the user create call to include the agreedOfTermsOfServices that wasn't previously being saved.
Run this locally, create a public account, check the db that the agreedToTermsOfService is set to true for that user.
=> fix: update create call

api/src/services/application-flagged-set.service.ts, api/src/services/listing.service.ts, api/test/unit/services/application-csv-export.service.spec.ts, api/test/unit/services/application-flagged-set.service.spec.ts, api/test/unit/services/listing.service.spec.ts
Pulls the following commit from core:
* fix: add the ability to disconnect community types
=> fix: add the ability to disconnect community types (#4153)

sites/partners/src/components/shared/NavigationHeader.tsx, sites/public/package.json, yarn.lock
Pulls over the following commit from core:
https://github.com/bloom-housing/bloom/pull/4162
=> fix: lottery rebase issues (#4162)

sites/public/src/pages/_app.tsx
https://exygy.slack.com/archives/C02G1S19QA2/p1719600993212059
Addresses the above issue in Slack
Ensure the search modal on the homepage works
=> fix: search issues

api/prisma/seed-staging.ts, sites/partners/cypress/fixtures/application.json, sites/partners/cypress/fixtures/householdDetailsOnlyData.json, sites/public/cypress/mockData/applicationData.ts
This PR addresses #691
Re: the issue, there seems to be a data problem (and possibly a bug causing that data issue) in production re: studio/SRO units and numBedrooms, but that isn't addressed here. This PR simply addresses seed data for local dev/testing.
Run the DB seed, and then check that listing filtering works as expected.
=> fix: studio unit types in seed data

sites/public/src/pages/applications/contact/address.tsx, sites/public/src/pages/applications/household/member.tsx
This PR contains the Core PR: https://github.com/bloom-housing/bloom/pull/4175
=> release: use the correct error keys for State and Zip

sites/public/src/pages/applications/review/confirmation.tsx, sites/public/styles/overrides.scss
This PR contains Core PR https://github.com/bloom-housing/bloom/pull/4173
=> release: application confirmation styling updates based on design QA

api/src/services/application-csv-export.service.ts
Fix for issue found during the bug bash
=> fix: programs and preference null check

shared-helpers/src/views/multiselectQuestions.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx, sites/partners/src/lib/applications/formatApplicationData.ts, sites/public/__tests__/pages/applications/preferences/all.test.tsx, sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
This PR addresses #3835
This pulls over the PR from core
=> fix: radio preferences don't show description and geocoding fields (#3918)

api/prisma/migrations/16_lottery_total/migration.sql, api/prisma/schema.prisma, api/src/controllers/lottery.controller.ts, api/src/dtos/applications/application-lottery-total.dto.ts, api/src/dtos/listings/listing-update.dto.ts, api/src/dtos/listings/listing.dto.ts, api/src/dtos/lottery/lottery-public-total.dto.ts, api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/application.service.spec.ts, api/test/unit/services/google-translate.service.spec.ts, api/test/unit/services/listing.service.spec.ts, api/test/unit/services/lottery.service.spec.ts, api/test/unit/services/script-runner.service.spec.ts, api/test/unit/services/translation.service.spec.ts, shared-helpers/src/types/backend-swagger.ts, sites/partners/__tests__/lib/helpers.test.ts, sites/partners/cypress/support/commands.js, sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/lib/helpers.ts, sites/partners/src/lib/listings/formTypes.ts, sites/public/src/pages/account/application/[id]/lottery-results.tsx
Pulls over the following commits from core:
=> feat: lottery results view, date formatting, re-run

sites/public/src/pages/index.tsx
listing notification sign up page was not linking properly 
this should fix
=> fix: notification url fix

api/src/services/listing.service.ts, api/src/services/lottery.service.ts, api/test/integration/lottery.e2e-spec.ts, api/test/unit/services/lottery.service.spec.ts
Pulls over the below commit from core
=> fix: dont send lottery emails to duplicate applications (#4346)

api/src/services/application-exporter.service.ts
releases https://github.com/bloom-housing/bloom/pull/4329 to doorway
=> feat: switching to write stream and sequential building (#4329)

api/src/services/email.service.ts, api/src/views/listing-opportunity.hbs
=> fix: convert single quote entities in Opportunities email

api/src/controllers/script-runner.controller.ts, api/src/services/auth.service.ts, api/src/services/script-runner.service.ts, api/test/unit/services/auth.service.spec.ts, api/test/unit/services/script-runner.service.spec.ts, sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx, sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx, sites/partners/src/pages/application/[id]/index.tsx
This PR addresses [#4193](https://github.com/bloom-housing/bloom/issues/4193)
Creates a script that does the following two things:
- Pulls over all partner users in HBA tied to at least one listing in the requested jurisdiction. Then ties it to the same listing in Doorway
- Pulls over all public users in HBA that have at least one application submitted in the requested jurisdiction. Then copies over all of those applications to Doorway
- No PII is carried over for the applications
This requires the previous jurisdiction scripts to be run so the following steps need to be run:
- Do a reseed locally
- Start up the app locally and go to the swagger api http://localhost:3100/api.
- Login via the api to the admin account http://localhost:3100/api#/auth/login.
- Go to Heroku and get the DB …
=> fix: add user and application import scripts

api/prisma/migrations/18_copy_of_reference/migration.sql, api/prisma/schema.prisma, api/src/services/listing-csv-export.service.ts, api/src/services/listing.service.ts, api/test/integration/listing.e2e-spec.ts, api/test/unit/services/listing.service.spec.ts
This PR addresses [#(806)](https://github.com/metrotranscom/doorway/issues/806)
Releases: https://github.com/bloom-housing/bloom/pull/4375
Run partner portal and api and login as a admin user.
Have the listing id for the listing you would like to duplicate.
Fill out the payload for listings/duplicate. Set storedListing.id to the above.
Click the listing export button in the parter portal.
Open the listing csv and view/verify the new columns.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you …
=> release: record of listing copy (#4375)

sites/public/cypress/support/commands.js, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/pages/applications/household/add-members.tsx
Pulls from Core:
* bloom-housing/bloom#4385
=> fix: household members link on application review (#4385)

api/package.json
Releases: https://github.com/bloom-housing/bloom/pull/4388
=> fix: may the force be with you (#4388)

api/src/dtos/users/confirmation-request.dto.ts, api/test/integration/application.e2e-spec.ts, api/test/integration/listing.e2e-spec.ts, api/test/integration/lottery.e2e-spec.ts, api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts, api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts, api/test/integration/permission-tests/permission-as-public.e2e-spec.ts, api/test/integration/user.e2e-spec.ts, api/test/unit/services/auth.service.spec.ts
This PR addresses  [#(4361)](https://github.com/bloom-housing/bloom/issues/4361)
Release: https://github.com/bloom-housing/bloom/pull/4389/
Run e2e tests locally.
=> release: flaky backend tests (#4389)

api/src/main.ts, api/src/services/application-exporter.service.ts, api/src/utilities/custom-exception-filter.ts, api/test/integration/custom-exception-filter.e2e-spec.ts, api/test/unit/services/application-exporter.service.spec.ts, api/test/unit/utilities/custom-exception-filter.spec.ts
Releases https://github.com/bloom-housing/bloom/pull/4362
=> fix: if programs is null no longer errors (#4362)

api/src/services/application.service.ts
Releases: https://github.com/bloom-housing/bloom/pull/4401
=> feat: exposes pref unit type (#4401)

sites/public/.env.template, sites/public/next.config.js, sites/public/src/lib/hooks.ts
Releases: https://github.com/bloom-housing/bloom/pull/4402
=> fix: exposing more closed listings (#4402)

ci/buildspec/migrate_stop_backend.yml, ci/buildspec/update_ecs.yml
This adds a private ECS service to the backend CI Build 
The only things that have changed are the buildspec files and config files for the dev builds. Feel free to check them out. Other than that. A successful build will verify it.  
=> feat: adding private backend service

api/src/passports/jwt.strategy.ts, api/test/unit/passports/jwt.strategy.spec.ts
=> fix: add correct error message for outdated password

api/src/controllers/auth.controller.ts, api/src/controllers/lottery.controller.ts, api/src/controllers/script-runner.controller.ts
releases: https://github.com/bloom-housing/bloom/pull/4374
=> fix: applying pass key to endpoints that were missing it (#4374)

sites/public/src/pages/applications/start/autofill.tsx
This PR addresses [#(insert-number-here)](https://exygy.slack.com/archives/C02G1S19QA2/p1730831837435289)
With the new users in Doorway that were ported over from SMC there is issues when trying to use autofill. Specifically when getting the most recent application there are many places in the code that assumed the applicant and address information exists. These ported over applications do not have any of this information because it was asked to just carry over the bare minimal information (confirmation code, id, etc) 
Because it doesn't make sense to do autofill if this information doesn't exist this PR checks if `applicant` exists on the application when deciding to go to the autofill page or not.
There are two flows that should be tested. One is harder than the other
Application with …
=> fix: skip autofill if no applicant data

api/yarn.lock
=> fix: no more ^

api/prisma/migrations/20_create_feature_flag_table/migration.sql, api/prisma/schema.prisma
This PR addresses [#(1287)](https://github.com/bloom-housing/bloom/issues/1287)
Creates new feature flag table with desired fields.
Run migrations locally. Open query and insert a record into the table.
=> feat: create feature flag table (#4475)

api/package.json, api/yarn.lock
Fixes dev to add back typescript dependency
=> fix: typescript

build/docker/Dockerfile.backend
Adds line to hopefully alleviate openssl issue.
https://stackoverflow.com/questions/79269631/prisma-openssl-version-issue
Thoughts and prayers
=> fix: apk add openssl to docker

build/docker/Dockerfile.backend
We need symlinks at ever step we call from node
=> fix: docker even more symlinks

ci/buildspec/update_ecs.yml
=> fix: always deploy internal api

sites/public/src/components/account/ApplicationsView.module.scss
This PR addresses #952 
Adds gap to list item. Tbh not sure if thats best solution, but i think it's beneficial anyway
Go to my applications, Accepting applications now should be in 2 lines.
=> fix: add gap to side panel list item

sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
This contains the following Core PR:
* bloom-housing/bloom#4535
=> release: clear household members for Submit & New in Applications (#4535)

api/prisma/seed-helpers/translation-factory.ts, api/src/controllers/script-runner.controller.ts, api/src/services/email.service.ts, api/src/services/script-runner.service.ts, api/src/views/lottery-published-applicant.hbs, api/test/unit/services/email.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This contains the following core PR:
* bloom-housing/bloom#4506
=> release: update translations and sign in link for lottery email (#4506)

api/src/services/application-exporter.service.ts, api/src/utilities/application-export-helpers.ts
This PR addresses #1080 
This PR addresses the following bugs:
1. If there is a period in the name of a preference the CSV export doesn't work for the selected fields
2. If there is a period in the text of the option in a preference the CSV export didn't work for the address, name, and relationship columns
3. If there is more than one option of a preference that asks for name and relationship it potentially didn't put it in the right column of the CSV export
This can be done by updating the seeded data, but here are the steps to manually test
1. Create a preference that has the following criteria
* A period in the middle of the title
* Multiple options that asks for address, name, and relationship
* At least one of the above option has a period in the middle
2. Attach that preference to a …
=> fix: update how csv generates preferences

api/src/dtos/script-runner/data-transfer.dto.ts, api/src/services/script-runner.service.ts, api/test/unit/services/script-runner.service.spec.ts, shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1053
This changes the public user transfer script to be paginated into 5k chunks
- pull down a backup of hba prod
- stand up the doorway api
- run through the import scripts aiming at your local version of the hba prod db
=> feat: paginating public user transfer

sites/public/src/layouts/max-width.module.scss, sites/public/src/layouts/max-width.tsx, sites/public/src/pages/404.tsx, sites/public/src/pages/_error.tsx
Releases the below commit from core
=> refactor: max width layout (#4500)

.github/dependabot.yml
=> feat: add dependabot yaml

ci/buildspec/migrate_stop_backend.yml
I had to add the ADMIN_ACCOUNTS variable to the docker run step to get it set so I can add the admin accounts for perf testing. 
=> fix: multiple admin accounts

ci/buildspec/migrate_stop_backend.yml
=> fix: missed a dash in the variable set

api/.env.template, api/src/services/auth.service.ts
=> feat: making https and same site configurable

api/test/integration/listing.e2e-spec.ts
This releases: https://github.com/bloom-housing/bloom/pull/4743 
a flaky api test fix
=> fix: flaky test updates (#4743)

shared-helpers/src/utilities/formKeys.ts
Issue: https://github.com/metrotranscom/doorway/issues/1100
Alameda county dropdown on partner's site now includes alameda
log into the partner's site, go to create a listing, you should see the county dropdown now has the Alameda option
=> feat: alameda count is ON

api/src/services/script-runner.service.ts
All public users now transferred
forces an order by of the user id to get around postgres issue
run scripts locally
=> fix: all users now transfered

.github/dependabot.yml, README.md
This PR addresses [#(4739)](https://github.com/bloom-housing/bloom/issues/4739)
Aligns Dependabot config file with core. This turns on version upgrades and standardizes Dependabot PRs for security and version upgrades.
The file does the following:
- Checks for all npm (yarn maps to npm) security and version dependency upgrades
- Sets the interval to weekly
- Groups together minor and patch level upgrade PRs. Major upgrades will get their own PRs
- Checks for docker security dependency updates
Dependabot config file option documentation can be found [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference)
Review file and compare to the documentation of each option. …
=> feat: align dependabot config file (#4910)

sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx, sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
Release of https://github.com/bloom-housing/bloom/pull/5000
=> feat: add unit groups unit types to paper form (#5000)

README.md
Releases the below commit from core, just simple README updates
=> docs: update readme (#4538)

sites/public/src/components/shared/CustomSiteFooter.module.scss
Releases the below commit from core
=> fix: site footer rtl (#5010)

shared-helpers/__tests__/unitTypes.test.ts, shared-helpers/src/utilities/unitTypes.ts, sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx, sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx, sites/public/__tests__/pages/account/application/[id]/index.test.tsx, sites/public/src/components/applications/SubmittedApplicationView.tsx, sites/public/src/components/shared/FormSummaryDetails.tsx, sites/public/src/lib/applications/ApplicationConductor.ts, sites/public/src/lib/applications/PreferredUnitSizeStep.ts, sites/public/src/lib/helpers.tsx, sites/public/src/pages/applications/review/summary.tsx, sites/public/src/pages/applications/start/autofill.tsx
Release of https://github.com/bloom-housing/bloom/pull/5037
=> fix: update unit groups displayed if needed (#5037)

api/src/controllers/script-runner.controller.ts, api/src/dtos/script-runner/data-transfer.dto.ts, api/src/services/script-runner.service.ts
This PR addresses [#5201](https://github.com/bloom-housing/bloom/issues/5201)
When porting over Alameda and SMC data from HBA we did not carry over all of the application data. Some of this data is now required by the Doorway team so we need to run a script to bring it over. 
This PR adds a new script run that adds additional data as outlined in [this doc](https://docs.google.com/spreadsheets/d/1wL0--UQLyTBzndxhZ49s5t0uoD67QjiAKP8Gy-myXzg/edit?gid=1720430781#gid=1720430781). Specifically you can find the fields in column I (Alameda/SMC Data Transitioned For Reference)
This is not the easiest to test, but you can do the following steps:
1. Run the staging seed, start up the API and go to http://localhost:3100/api
2. login with an admin user
3. Run the following script runs using either …
=> fix: add additional application data script

sites/public/src/pages/listing/[id]/[slug].tsx
=> fix: switch log from console to logger

sites/partners/__tests__/pages/users/index.test.tsx
=> fix: make user test more deterministic
