metrotranscom/doorway

- backend/core/.env.template
- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
- sites/public/src/pages/index.tsx
2 changes in this PR, both meant to facilitate development
1) We already have our internal set of .env file changes, making those changes to the template to codify informal knowledge
2) Adding a door emoji to the title and header of the page. This change is meant to be temporary until the Doorway UI is finalized and becomes distinct from Bloom. Why do this? there are so many different versions of Bloom/etc that it may be useful to be able to visually identify whether or not the demo is a Bloom demo or a Doorway demo.
> Update .env.template file with new defaults + Doorway signifier

- docker-compose.yml
@chriscasto and @ifranch found that there is a collision between local postgres and the containerized postgres's port. This avoids that collision by forwarding to a different local port, as well as updating the pguser to be consistent with our implementation
I tested this change by `docker-compose up`ing WITH a local postgres running, and not running into the port error.
> Forward container Postgres to a different port than local Postgres

- .github/workflows/codeql.yml
- .github/workflows/integration_tests.yml
- .github/workflows/lint.yml
- .github/workflows/unit_tests_backend_core.yml
- .github/workflows/unit_tests_shared_helpers.yml
- .github/workflows/unit_tests_sites_partners.yml
- .github/workflows/unit_tests_sites_public.yml
See title.
I tested this by iterating on my personal fork. See https://github.com/lisunshiny/bloom/pull/1 for an example of this working.
I also disabled the version-packages GitHub action since it was just failing every time and I'm not sure that we need it, so the hope is that the green check mark and red x are descriptive once this is merged.
It is not super DRY, but given that this is a patch while we prop up a Docker-based CI/CD system, I'm not super worried about it.
> Run unit and integration tests on each PR to main via Github Actions + enable linting and CodeQL

- .github/workflows/integration_tests.yml
- backend/core/test/listings/listings.e2e-spec.ts
There were 2 issues here:
1. I did not add the `joi` required env variables, so I added those in the GitHub action.
2. After adding that the tests around checking for only the bay area  in `listings.e2e-spec.ts` started legitimately failing. I looked into this and it is because the `authz.e2e-spec.ts` test adds new jurisdictions and listings under those jurisdictions, saving them to the DB. I didn't catch this when testing locally becuase I only ran `listings.e2e-spec.ts` in isolation. 
Given that other tests do db inserts, these tests don't make sense (and I think that what authz.e2e-spec.ts is testing is very important and I don't want to delete that). So instead I update the test to just check that there is a Bay Area jurisdiction and there are listings associated with it.
To test this …
> Fix integration tests

- backend/core/src/seeder/seed.ts
- backend/core/test/listings/listings.e2e-spec.ts
Helps with testing #11 
Update the seed script to show that the listings are from the Doorway script so that its easier to tell at a glance what is local vs not.
* Reseed
* Verify that all listings have the Doorway namespace
> [easy] chore: update seed script with Doorway namespace

- shared-helpers/__tests__/pdfs.test.ts
- shared-helpers/__tests__/photos.test.ts
- shared-helpers/src/utilities/pdfs.ts
- shared-helpers/src/utilities/photos.ts
- shared-services/index.ts
- shared-services/src/files/cloudinary-file-uploader.ts
- shared-services/src/files/cloudinary-file.service.spec.ts
- shared-services/src/files/cloudinary-file.service.ts
- shared-services/src/files/file-config.ts
- shared-services/src/files/file-service-provider.spec.ts
- shared-services/src/files/file-service.interface.ts
- shared-services/src/files/file-service.provider.ts
- sites/partners/src/components/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx
- sites/partners/src/components/listings/PaperListingDetails/sections/DetailListingPhoto.tsx
- sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
- sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
- sites/partners/src/components/listings/PaperListingForm/sections/ListingPhoto.tsx
- sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
- sites/public/src/components/listing/ListingView.tsx
This PR addresses #20 
Create a FileServiceProvider which instantiates FileService. The provider reads environment variables to create a config object determining which implementation of the file service to use, and any necessary keys/variables. Currently the only available implementation is Cloudinary which is why it is hardcoded, in the future AWS S3 will be implemented as a separate option and which service to use will be configurable.
Added unit tests for the new class and updated existing unit tests where needed.
Also verify that the public and partners sites can both be loaded, and tested adding a new listing photo in the partners site, which calls both putFile() and getDownloadUrlForPhoto().
- Read and understand the issue, and ensure the author has added QA …
> feat: add a provider for FileService which also creates a FileConfig object

- backend/core/src/listings/listings.controller.ts
`mapTo(PaginatedListingDto` is done on the /listings endpoint and does a lot to consolidate the Listing object and adds the urlSlug, so we need to add that back in here.
I didn't add a test since I think this code is getting deprecated soon and this is a hotfix to get it working again
before -- the URL is `listing/[id]/undefined`
after it is `listing/[id]/[urlSlug]`
> fix: add urlSlug back to local listings

- sites/public/src/components/listings/ListingsCombined.tsx
- sites/public/src/components/listings/ListingsList.tsx
- sites/public/src/components/listings/ListingsMap.tsx
- sites/public/src/pages/listings.tsx
* refactors the listing list into a new component
* makes a new component with the combined listinglist and listingmap
* fixes a warning I introduced in #55 
* styles with flex to add the two column layout
This CL covers layout only -- styling will happen in a subsequent diff.
> Update /listings page layout with combined map/list view

- backend/core/src/listings/combined/combined-listing-filter-keys-enum.ts
- backend/core/src/listings/combined/combined-listing-filter-params.ts
- backend/core/src/listings/combined/combined-listing.entity.ts
- backend/core/src/listings/combined/filter-type-to-field-map.ts
- backend/core/src/migration/1681750950575-addCombinedExternalListings.ts
- backend/core/src/seeder/seeds/listings/external-listings-seed.ts
- backend/core/test/listings/listings-combined.e2e-spec.ts
- backend/core/test/listings/listings.e2e-spec.ts
This PR addresses #64
This issue adds two new filters (city and county) and adds a e2e tests for both.  The original issue listed `num_bedrooms` as a filter to add as well, but since it was already available this just adds an e2e test for it.  The only filter not added here is for monthly rent.  This field is stored as a string, making mathematical comparisons like less/greater than (which would be necessary for this filter) impossible to implement without some additional changes.  Further review and discussion on these changes is forthcoming, but in the meantime there is nothing blocking the addition of the other filters.
All changes have corresponding e2e tests, so you can verify automatically by running `yarn test:e2e:local` in the `backend/core` directory.  There are lot of tests and …
> feat: add city and county filters

- sites/public/src/components/listings/ListingsMap.tsx
- sites/public/src/lib/helpers.tsx
This PR addresses #107 
- When a pin on the map is clicked, open an info window that shows the listing card for that specific listing. This uses the existing ListingCard component.
- Refactor the existing code to create the listing card so there is a shared method to get just one listing card that can then be called by the map.
Screenshot of the listings page below. See how the listing card in the info window is the same as the existing card on the right side column and how the indices match.
To test this feature, bring up the public site and go to the listings page. You will need to have a Google Maps API key specified in the environment variables for the public site. Click on any listing pin to open the info window, and then click on the x in the top right corner of the window to close …
> feat: add info window with the listing card that opens on click on map markers

- doorway-ui-components/src/global/text.scss
- doorway-ui-components/src/global/tokens/borders.scss
- doorway-ui-components/src/navigation/LanguageNav.scss
- doorway-ui-components/src/navigation/LanguageNav.tsx
See our Figma file for mocks.
Before:
After:
https://github.com/metrotranscom/doorway/assets/10789523/60686268-ccfc-48da-bcf7-519757e62874
> feat: restyle language bar to doorway version

- doorway-ui-components/src/config/NavigationContext.tsx
- doorway-ui-components/src/global/text.scss
- doorway-ui-components/src/page_components/listing/ListingCard.scss
- doorway-ui-components/src/page_components/listing/ListingCard.tsx
- sites/public/src/lib/helpers.tsx
This is one of many ways to fix the issue where hover states are not working on the ListingCard component.
The bug here was that the way that the entire card was made clickable was via an `a:after` element with a very high z index covering the whole card. This element even went over the header submenu (which is why the header submenu was messed up in #124).
We still want the card to be clickable (and using the anchor tag instead of js click handlers is I assume an accessibility thing) so I added a synthetic click event when someone clicks on the component itself onto the anchor tag. This shouldn't break screen readers etc. since the anchor tag is still there.
(note that the absolute most semantically correct way to do this is probably to just make the `<section>` tag an `<a> `tag, but …
> feat: make listing card clickable without breaking hover states

- sites/public/src/components/listings/ListingsMap.tsx
This fixes a bug where clicking the same marker on the listings map twice doesn't open the info window the second time. The issue was that openInfoWindow is still true so clicking on the marker doesn't change its state. Now, closing the info window resets the state to false.
- Go to the listings page on the public site.
- Click on a marker, this should open a pop up info window.
- Close the info window.
- Click on the same marker again, this should open the same info window.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not …
> fix: update state to not show info window on close click

- sites/public/src/components/listings/ListingsMap.tsx
- On mobile, scroll down to the correct listing on the listings list when a map pin is clicked. For example if pin "12" is clicked, the listings list will now show listing 12.
- On desktop, keep the existing behavior where a listing card pops up in a window when the marker is clicked.
This fixes the issue where the info window looks bad on mobile since the picture is too narrow, plus the screen is too crowded with both the pop up window and the hybrid listings list.
- Bring up the public site and go to the listings page.
- On desktop, click on a map pin and verify that an info window pops up with the corresponding listing.
- Close the info window.
- Switch to mobile by using the Chrome Device Emulator.
- Refresh the page for a better experience since this will recenter the map.
- Click on …
> feat: change behavior for marker click on mobile

- sites/public/src/components/listings/ListingsCombined.module.scss
- Fixes a bug which causes the listings map to not show on desktop. I must have introduced this bug when rebasing with main in https://github.com/metrotranscom/doorway/pull/143.
- Go to the listings site on desktop and make sure you can see the listings map.
> fix: map display on desktop

- doorway-ui-components/src/blocks/ImageCard.scss
- doorway-ui-components/src/global/text.scss
- doorway-ui-components/src/page_components/listing/DoorwayListingTable.scss
- doorway-ui-components/src/page_components/listing/ListingCard.scss
- doorway-ui-components/src/page_components/listing/ListingCard.tsx
- Change location of "See details" button for desktop vs mobile
- Update margins and padding for mobile listing card as well as desktop where needed
- Round the corners of the image card
- Update font sizes and colors according to Figma specs
- Add border to the bottom of each listing card
- Center listing card content to the left for mobile
Mobile before:
Mobile after:
Desktop before:
Desktop after:
iPad before:
iPad after:
Go to the listings page and try using different devices with the chrome developer tools device emulator
> feat: style mobile listing cards

- doorway-ui-components/src/global/app-css.scss
- doorway-ui-components/src/global/blocks.scss
- doorway-ui-components/src/global/doorway/backgrounds.scss
- doorway-ui-components/src/global/tables.scss
- doorway-ui-components/src/global/tokens/colors.scss
- doorway-ui-components/src/notifications/ApplicationStatus.tsx
- doorway-ui-components/src/page_components/listing/ContentAccordion.scss
- shared-helpers/src/views/summaryTables.tsx
- sites/public/src/components/listing/ListingView.tsx
This PR introduces some new CSS background variables that are more reasonable for the various views on the listing page and uses them to style the listing page, effectively making it not look ridiculously broken.
This is the beginning of restyling the page based on the spec and followup PRs will continue to add styling. The benefit of doing this first is that it adds a new precedent for doorway background colors and makes the listing page look decent for demos and other things.
https://github.com/metrotranscom/doorway/assets/10789523/cbe01835-b0dd-4e45-8fe4-c29eb84c00d2
https://github.com/metrotranscom/doorway/assets/10789523/e522fefc-cc38-483a-909e-d0b8dc52c07c
> feat: update colors on the listing page to be more reasonable

- sites/public/src/components/listings/ListingsCombined.module.scss
- sites/public/src/components/listings/ListingsCombined.tsx
- sites/public/src/components/listings/ListingsMap.tsx
Fix a bug in the mobile listings page when clicking on map pins in the expanded map view. Now when a pin is clicked, the listings list comes up with the clicked on listing. I also considered opening an info window with the listing card (like what is done on desktop), but the listing card style looks bad since it's narrower than the default on mobile and it would need considerable restyling.
This also fixes a bug introduced in https://github.com/metrotranscom/doorway/pull/155 that makes the height of the listings combined component too tall, which means there is vertical scroll on the listings page on mobile. Since there is now a search modal at the top between the header and the ListingsCombined component, we need to subtract its height as well. I checked that its height is always 44.5px, …
> feat: show listing on listings list when a map pin is clicked on mobile

- sites/public/src/layouts/LayoutWithoutFooter.tsx
- sites/public/src/layouts/application.tsx
- sites/public/src/lib/helpers.tsx
This PR does a refactor with two small feature changes:
1.  It highlights the active link vs just always highlighting the welcome link.
2. It fixes #106, the issue where someone logged in will see the logged in menu
It changes the copypasta that was the LayoutWithoutFooter component's <SiteHeader> to live in helpers.tsx.
I did this in anticipation of updating the SiteHeader with the correct links to the help center.
I tested this by making sure that /listings (no footer template) and / (application template) both loaded fine with the right highlighted link.
> refactor: update the SiteHeader component to share a single function [mostly a no-op]

- sites/public/src/components/listings/ListingsCombined.tsx
- Change swiping behavior for listings page on mobile so when the listings list is swiped up, the page doesn't also get scrolled all the way down to the footer.
- On mobile, go to the listings page and you'll see the hybrid page. Swipe up on the listings list. This will show you just the expanded listings list without going to the bottom of the page and showing the footer.
> feat: prevent scrolling on swipe

- doorway-ui-components/src/forms/Field.scss
- doorway-ui-components/src/forms/FieldGroup.scss
- doorway-ui-components/src/forms/FieldGroup.tsx
- doorway-ui-components/src/headers/DoorwayHero.scss
- sites/public/src/components/listings/search/LandingSearch.module.scss
- sites/public/src/components/listings/search/LandingSearch.tsx
- sites/public/src/components/listings/search/ListingsSearchCombined.tsx
- sites/public/src/components/listings/search/ListingsSearchModal.tsx
Make a few styling changes to the landing search component as well as the listings search where necessary. There are still a few styling changes needed that are not included in this PR.
- Make San Francisco county field span both columns. Both for landing search and listings search.
- Change county checkmarks to white. Only for landing page, listings still uses black as intended.
- Fix buttons being cutoff by adding extra padding around components. Only for landing page, was already working fine for listings search.
- Use same style for listings search county names as what is already used for landing search. Updates font size, spacing, color.
- Stop county names from shifting right when clicked. Only for landing page, was already working fine for listings search.
- Removes light blue …
> feat: landing search style fixes

- sites/public/src/pages/index.tsx
- Fixes build error by adding the right import. FormOption was duplicate but I deleted one of them to use the same one across different pages, and the import was not properly updated.
Test: run yarn build for the public site
> fix: build error

- doorway-ui-components/src/actions/Button.scss
- sites/public/src/components/listings/search/LandingSearch.tsx
- Add an override class for the landing search bedroom size buttons. There is already existing logic to style the buttons with the secondary class when selected, so this override applies to secondary buttons.
- Update the background, border and text color to match the mocks. Add hover and active state colors that are one and two shades darker, respectively.
- Go to the landing page.
- Verify that the "Any" button is selected by default and has a royal blue background and white text.
- Click on any other bedroom size button and verify that it turns that shade of blue.
- Hover over the button and check that it turns a shade darker.
- Go to the listings page and open the filters modal.
- Verify that the bedroom and bathroom size buttons are still light blue when selected, not royal blue.
> feat: change color of landing search buttons when selected

- sites/public/src/components/listings/ListingsMap.tsx
Fixes issues related to how listings are displayed on mobile when a map pin is displayed by scrolling the appropriate listing to the bottom of the page, not the top. The behavior of clicking on a map pin on mobile was broken when the footer was added back to the listings page and looked like this, putting the listing at the top and including the footer
By passing false for the alignToTop input, now the listing card is aligned at the bottom of the page. Now when a map pin is clicked on, either from the hybrid view or from the map view, the map is still visible and the listings list is scrolled to the listing card, aligned with the bottom.
This kills two birds with one stone because the "See details" button is always visible now. The downside is that for listings with many bedroom sizes, …
> feat: scroll bottom instead of top of listing card into view

- sites/public/src/components/listings/ListingsCombined.tsx
- sites/public/src/components/listings/ListingsList.tsx
- sites/public/src/components/listings/search/ListingsSearchCombined.tsx
- sites/public/src/components/listings/search/ListingsSearchModal.tsx
This PR addresses empty listings clear filters button clears the filters and reloads the page with an empty, default query.
emtpy results:
clicking clear all filters
- Also review the acceptance criteria on the Netlify deploy …
> fix: clear filters button on empty listings results

- sites/public/src/components/listing/GetApplication.tsx
Increase the spacing in between text and button for the application section of the listing page when there is a paper application.
Before: 
After: 
I don't have any seeded listings with paper applications so I made the change directly on dev to test it. There is also a GetApplication component in UIC https://github.com/metrotranscom/doorway/blob/main/doorway-ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx but that is not what is used, the listing view component uses the GetApplication component from the public site.
> feat: add extra margin in application section for paper application

- doorway-ui-components/src/forms/FieldGroup.scss
- sites/public/src/components/listings/search/LandingSearch.tsx
- sites/public/src/components/listings/search/ListingsSearchModal.tsx
This PR addresses [#18](https://github.com/bloom-housing/Bloom-Doorway/issues/18)
Currently, the checkboxes on the home page in the search box and the listings page in the filter drawer have their label text misaligned.
The label text on these two forms should be centered with the check. The cause was new custom styles added to the checkboxes. The long term solution would be CSS variable overrides once Doorway is on UIC.
- …
> fix: align checkboxes

- sites/public/src/components/listings/search/LandingSearch.tsx
- sites/public/src/components/listings/search/ListingsSearchModal.tsx
This PR addresses [#15](https://github.com/bloom-housing/Bloom-Doorway/issues/15)
These changes address the fact that rent fields were accepting the negative sign and "e" along with changing via scroll. Also, it was allowing decimal points but that would also break the filtering results.
**Disclaimer:** This is undoubtedly a hacky approach and a more sustainable approach should be implemented [here](https://github.com/bloom-housing/Bloom-Doorway/issues/16). The difficulty came from the fact that our currency formatting utilizes react hook forms but these two forms were made with a custom react state form object and their own updateValue functions. This was the quickest way I found to integrate our formatting with their value setting. Other approaches such as introducing the formatting …
> fix: rent formatting hack

- backend/core/src/migration/1692890494691-ami-120-updates.ts
- sites/public/cypress/e2e/pages/submit-application.spec.ts
This PR addresses #311 
This fixes a small bug in the ami 120% script. The Select statement returns an array of items so we need to get the first one in order to get the correct "items".
Note: This migration has not run on production, but has on staging. I will delete the row for this migration in staging before merging
Since the AMI charts mentioned in the migration are not in the seeded data I'd recommend the following steps to test this.
- Go to main branch locally and go back one commit (Should not have `fix: add 120% ami info` commit on your machine)
- Do a reseed
- Pull in the code from this branch
- Change one of the names of the AMI in this new migration file to one we have in the seeding (e.g "San Jose TCAC 2021") 
- run `yarn db:migration:run`
- Check that the database has the …
> fix: change ami update migration

- ci/buildspec/build_public.yml
Hopefully the last change needed all the professional partners flag flipped
> fix: add show professional partners to build public

- build/docker/Dockerfile.sites-generic
One location was missed when adding the `SHOW_PROFESSIONAL_PARTNERS` arg to the build step. I've tested this in the test pipeline and it successfully turned on the feature in the dev environment
> fix: add last show professional partners spot

- backend/core/src/shared/uploads/aws/amazon-s3-file-service.ts
The latest release of @aws-sdk makes a typing change that breaks a place in our code. Specifically this commit: https://github.com/aws/aws-sdk-js-v3/commit/7d312220ce4d75c55a63e8ca1b3320fdb9bf152c changes the type from `StorageClass?: StorageClass | string;` to `StorageClass?: StorageClass;`
Due to the way Doorway is getting built for Docker it doesn't always grab the same version of dependencies that we expect. I plan on solving some of these issues with the improvements to the Doorway pipeline. But in the meantime here is a fix for this immediate issue to allow us the ability to release.
> fix: type fix for s3-file-service

- doorway-ui-components/src/global/text.scss
- doorway-ui-components/src/page_components/help-center/DoorwayLinkableCardGroup.scss
- doorway-ui-components/src/page_components/help-center/DoorwayLinkableCardGroup.tsx
- sites/public/src/components/listings/search/LandingSearch.tsx
- sites/public/src/components/listings/search/ListingsSearchModal.tsx
- sites/public/src/pages/index.tsx
This PR addresses #389 
After discussions with both product and design, it seems that a broader alignment of Doorway links is needed but not within the scope of this ticket. As a result, this ticket only does the following
1. Underline the "Dahlia" link on the home page search and the listings page filter modal
2. Underline the Bay Area Housing Finance Authority (BAHFA) link on the homepage 
3. Underline and update the color of all links within the partners and help center pages through the Doorway Linkable Card group. 
This partial color change is to address the issue with not finding links within those help pages while giving us time to resolve the contrast issues that come up if doing this globally. That follow up is captured [here](https://github.com/metrotranscom/doorway/issues/396). …
> fix: link updates

- backend/core/src/listings/dto/listing-published-create.dto.ts
- backend/core/src/listings/dto/listing-published-update.dto.ts
This PR addresses https://github.com/bloom-housing/Bloom-Doorway/issues/49
Background: the referral opportunity field was purposely removed from the frontend on Doorway but all of the backend logic still exists
A admin was recently unable to publish a listing because the "referralOpportunity" field was getting sent as `null` instead of `false`. I am unsure how this can happen as I am unable to get into that scenario using the UI. However, I was able to reproduce it by changing the field value when manually sending a call to the backend. 
This error can only happen on the publish flow since that is the only DTO that didn't have this field as optional
You should be able to still create and publish listings
- Read and understand the issue, and ensure the author has …
> fix: make referralOpportunity optional

- sites/public/next.config.js
- sites/public/src/components/listings/ListingsList.tsx
- sites/public/src/pages/listings.tsx
The map on the listings page of Doorway dev and staging stopped working after the most recent changes.
This is because we are not setting the google maps api key as a build env variable in the build step but rather just a runtime env variable. The latest change is now looking for the api key in a place that can only read the build time variables.
This change reverts the part of the change that is causing this. Ideally we would have all env variables be only runtime, but that will be a bigger endeavor 
How to test:
The listings page should work the same it usually does and the map should appear
> fix: get maps api key from server

- .github/workflows/codeql.yml
- .github/workflows/cypress_partners.yml
- .github/workflows/cypress_partners_la.yml
- .github/workflows/cypress_public.yml
- .github/workflows/etl.yml
- .github/workflows/integration_tests.yml
- .github/workflows/lint.yml
- .github/workflows/unit_tests_backend_core.yml
- .github/workflows/unit_tests_doorway_ui_components.yml
- .github/workflows/unit_tests_shared_helpers.yml
- .github/workflows/unit_tests_sites_partners.yml
- .github/workflows/unit_tests_sites_public.yml
- .github/workflows/version_packages.yml
- doorway-ui-components/.github/workflows/release.yml
Assigning to @ludtkemorgan 
- Upgrade codeql to V2 (v1 is deprecated)
- Minor formatting changes
Github action should be successful 
- [NA] I have reviewed the changes in a desktop view
- [NA] I have reviewed the changes in a mobile view
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] Any dependent changes have been merged and published in downstream modules
- [NA] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [NA] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- …
> Feat: Upgrade various github actions to supported versions

- tasks/import-listings/src/etl/transform/map.ts
With the latest mapping of the prisma object for the combined listing the images on the listings page don't work for external listings. This is due to the change from "images" to "assets". The latest change accounted for this, but did not consider that the images are in an array. so the "images" need to be set on each image rather than at the top level
- Make sure that the following env variables are set in backend/core and sites/public: `BLOOM_API_BASE=https://hba-0-3-alameda-staging.herokuapp.com`
- in backend/core run `yarn db:reseed:with-external:dev`. This will pull in the listings from hba staging environment
- Start up the app and on the listings page all external listings should have an image (unless they don't in the staging environment as well)
Steps to …
> fix: map images correctly for external

- api/package.json
- build/docker/Dockerfile.backend
- ci/buildspec/build_backend.yml
- ci/buildspec/migrate_stop_backend.yml
The AWS pipeline is failing for the following reasons:
- backend build fails because the unit tests are run before fully building. They are failing because there are missing environment variables. However, since nothing can get into the main branch without tests passing on the PR, I think it makes sense to disable the tests to make the build even faster.
- The dev migration script takes down the db and rebuilds it from scratch. Because of that we can't skip the migrations we will need to do in prod. I have updated the docker file to accommodate both use cases and have the dev migration not skip any of the migrations
> fix: updates to the pipeline

- api/package.json
- tasks/import-listings/package.json
Dev deployment in AWS is trying to use a database that doesn't exist
> fix: remove reference to bloom_prisma

- api/prisma/migrations/00_init/migration.sql
- api/prisma/migrations/01_change_to_prisma/migration.sql
- api/prisma/migrations/02_doorway_to_prisma/migration.sql
Ran into this error when running migrations on staging 
```
Migration name: 01_change_to_prisma
--
Database error code: 42P01
Database error:
ERROR: relation "map_layers" does not exist
```
This is because the geocoding feature was never released on Doorway until now so we need to initialize it for the first time
> fix: move map layer initialization in migration

- api/src/services/listing.service.ts
This PR addresses #529 
This PR fixes the issue where the listingsService.retrieve in account/applications.tsx was returning a 500 error from the listing translation services. This was traced back to language [here](https://github.com/metrotranscom/doorway/blob/9ffc4f20f00a6aba3f1b2d3f3affc7d9430ec331/backend/core/src/listings/listings.controller.ts#L117) being an empty string. When that empty string is passed to the service, it is treated as a value and therefore doesn't receive the default value of LanguageEnum.en that is set in the listing.service findOne call ([resource](https://www.studytonight.com/javascript/javascript-default-parameters#:~:text=As%20we%20can%20see%20in,values%20and%20are%20used%20as)). This PR adds an additional check to cover that empty string case.
I haven't yet …
> fix: cover empty string case

- sites/public/src/components/listing/ListingView.tsx
- sites/public/src/pages/listing/[id]/[slug].tsx
- sites/public/src/pages/preview/listings/[id].tsx
This PR addresses #575 
This change updates the logic around redirecting the user to sign in, the common app, or an external online application.
Previously, we were only checking if a user was signed in or not but this fails to account for listings linking to external applications. Now we get the onlineApplicationInfo first instead of just assuming isExternal is false as we were doing before.
This can be tested by taking an existing public listing adding a custom online application, and testing to see if the preview link and public link don't force you to sign in. Note, you must open these links in separate windows so you're not using the user profile of the logged in partner user.
- Review the …
> fix: online application checks

- sites/public/src/components/listing/ListingView.tsx
- sites/public/src/pages/listing/[id]/[slug].tsx
- sites/public/src/pages/preview/listings/[id].tsx
This PR addresses #575 
This is a follow up to https://github.com/metrotranscom/doorway/pull/576. I undid some of the changes so the external helper text (specific to HBA external listings and not all custom applications) shows when appropriate.
This can be tested by taking an existing public listing adding a custom online application, and testing to see if the preview link and public link don't force you to sign in. Note, you must open these links in separate windows so you're not using the user profile of the logged in partner user. Additionally observe that no helper text appears in either case!
- Pull the changes down locally and test that …
> fix: prevent helper text from showing on custom apps

- sites/public/src/lib/applications/AppSubmissionContext.ts
- sites/public/src/lib/applications/configInterfaces.ts
- sites/public/src/lib/hooks.ts
- sites/public/src/pages/applications/review/summary.tsx
- sites/public/src/pages/applications/start/choose-language.tsx
This PR addresses #582 
This fix adds the preview boolean to the application config in a way that it persists through the application. Additionally, this PR updates the redirect on the summary page so users can't race to the submit button and partners won't be redirected to the public listing rather than the preview listing.
This can be tested by logging in to the partner's site, preview a draft listings application (open link in new window so that session doesn't carry over via local host), and ensure you can fill out the application until the summary page. Then go to an open listing on the public side to ensure that the MA account checks are still in place.
- Review the code itself from a …
> fix: preview take2

- sites/partners/src/pages/api/adapter/[...backendUrl].ts
- sites/partners/src/pages/listings/[id]/edit.tsx
- sites/partners/src/pages/listings/[id]/index.tsx
- sites/public/src/logger.ts
- sites/public/src/pages/api/adapter/[...backendUrl].ts
> Fix: Expand Logger For Partner Site

- sites/public/src/pages/applications/financial/vouchers.tsx
Fixes missing string by ensuring the casing matches
> fix: missing string

- sites/partners/src/lib/applications/formatApplicationData.ts
This PR addresses [#issue](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/632)
Attempting to edit an applications fails to render the edit form page and displays page not found and an error message. This is caused by an if statement checking on `demographics.spokenLanguage` which may not be set at the time of edit. By allowing for spokenLanguage to be null, the edit page correctly renders.
Sign into partners site, navigate to a listing with applications submitted or submit an application of any type as long as spoken language is not set, go to the listings applications tab, click on an application, click `Edit`, edit form page should render.
Describe the tests that you ran to verify your changes. Please also list any relevant details for …
> Fix: Edit Application Fails to Render

- sites/public/src/pages/applications/review/terms.tsx
634
This PR addresses [#issue](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/634)
`data.agree` was already a boolean so comparing it to a string caused the new variable to always be false. Should assign the existing boolean to the new variable for sending to the api.
Go through the online application flow, at the last step open up network tab, agree to the terms and submit, check that the submit call had `acceptedTerms` set to `true` and that the response has the same, confirm in the db that it is set correctly.
Manually tested and ran public side unit and e2e tests.
Steps to …
> Fix: Agree To Terms Saves Correctly

- sites/partners/src/pages/api/adapter/[...backendUrl].ts
- sites/partners/src/pages/api/adapter/upload.ts
- sites/partners/src/pages/listings/[id]/edit.tsx
- sites/partners/src/pages/listings/[id]/index.tsx
- sites/public/src/lib/hooks.ts
- sites/public/src/pages/api/adapter/[...backendUrl].ts
- sites/public/src/pages/listing/[id].tsx
- sites/public/src/pages/listing/[id]/[slug].tsx
- sites/public/src/pages/preview/listings/[id].tsx
This makes the api pass key header on the public and partner sites optional. They will only be sent if the api pass key env variable is present
> feat: makes the pass key a contingent header

- shared-helpers/src/auth/Timeout.tsx
This PR addresses #560 
This PR updates the router we use from the NavigationContext of UI-C to Doorway-UI-C router which is used as a provider in the _app.tsx file. Ideally, we'd be off the Doorway-UI-C version all together but since this is such a specific fix, I decided it would be out of scope to do this alignment. Instead, it is captured here #645 
This takes a bit to test but it's worth it 🥳 
1. Update the IDLE_TIMEOUT env variable to 1
2. Run PR locally
3. Sign in to a public account
4. Leave that window alone and do something else!
5. When you remember come back and see that you've been redirected to the sign in page
You can reproduce the steps above on main to see that you'll end up on a blank screen.
- Read and understand the issue, and ensure the author …
> fix: match import with app file

- api/src/views/confirmation.hbs
This PR addresses #653 
hides `office hours` section when no office hours available.
Tbh couldn't test it locally, but it seem fairly straightforward
Fill application for listing with office hours, and then without.
You should receive email with / without `office hours` section.
> fix: office hours in email template

- sites/public/src/pages/create-account.tsx
This PR addresses #664 
passes default value to TOS checkbox input
On `http://localhost:3000/create-account` .
1. fill form 
2. press create account
3. check checkbox and close modal,
4. press create account
checkbox should have checkbox "checked" and ready to "finish"
> fix: use default value for accept TOS checkbox

- sites/public/src/components/listing/ListingView.tsx
This PR addresses #4135
This PR updates the logic to show the submit application section to account for the mailing and dropoff addresses to be undefined but the address type is same as leasing agent.
Create a listing with "Are postmarks considered?" marked as Yes, a paper app attached, indicate a received by date & time, and with both the mailing address and the drop-off address marked as same as the leasingAgentAddress... the submit application section should show on the public side with the corresponding postmark information.
- Either (1) explicitly ask a clarifying question, (2) request …
> fix: include check for address type (#4136)

- sites/public/cypress/e2e/pages/application/contact/address.spec.ts
- sites/public/cypress/e2e/pages/application/household/member.spec.ts
- sites/public/cypress/support/commands.js
- sites/public/src/pages/applications/contact/address.tsx
- sites/public/src/pages/applications/household/member.tsx
This PR addresses #677 
This PR is meant to hide the "Do you work in" question from the common application with the least amount of changes. Given the turnaround on release on Monday, I only focused on hiding it on the applicant information and household member information page. 
This can be tested by filling out the common app and noticing that the question doesn't appear on the address page nor the household member section.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to …
> fix: hide do you work question

- api/.env.template
- api/src/services/user.service.ts
- api/test/unit/services/user.service.spec.ts
This PR addresses #4089 
This PR incorporates some points that @mcgarrye came up in discussing the previous [PR](https://github.com/bloom-housing/bloom/pull/4090) addressing this issue. Specifically in HBA, an alameda public user is able to log in to the san jose site and see applications from alameda in the san jose portal. Matching fully on the public url from the users jurisdiction would mean the forgot password experience is incorporating security that users aren't experiencing on the sign in page itself leading to a confusing experience. This issue is captured here #4119 
As a result of this, this PR just checks that a public user is not using the partners portal. **Additionally, this PR updates the env and env template to just include http://localhost:3001 to actually match the …
> fix: looser isUserSiteMatch (#4120)

- build/docker/Dockerfile.sites-generic
- sites/partners/__tests__/pages/listings/index.test.tsx
I missed one spot where backend/core is still referenced in the docker file. 
Also by pulling out backend/core we no longer have to mock a dependency on one of the test
> fix: remove last reference to backend in docker

- sites/public/src/pages/preview/listings/[id].tsx
PULLED FROM CORE: 
This PR addresses #4147 
This PR adds in language to the headers of the listings call on the preview page so that it matches the [slug.tsx] headers. This way the translation service is called within the listingService.findOne() call.
This can be tested by pulling this down locally, previewing a listing from the partner's side and see that most if not all strings are translating with the exception of a few particular fields such as "or one month's rent may be higher for lower credit scores" which are known by Sarah. If you wish you can uncomment the new line to see the difference.
- Pull the changes down locally and test that the acceptance criteria …
> fix: add language to headers (#4148)

- api/package.json
The reseed command in Doorway dev environment is failing because the ts-node package doesn't exist. I believe this is because we are only downloading the production node modules. 
This PR moves the ts-node package to the dependencies instead of devDependencies.
> fix: move ts-node to dependencies

- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
This PR addresses [#4113](https://github.com/bloom-housing/bloom/issues/4113)
The new translation keys are needed for the community type added to Alameda
You can't create a listing that has this community type so you will need to pull the prod HBA listings over. 
This can be done by going to `/tasks/import-listings` and run `yarn install && yarn build && yarn import:run:local:prod` 
Then you should see this property:
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review …
> fix: new translations for housing vouchers

- build/docker/Dockerfile.backend
The AWS pipeline is broken due to docker build step of the backend failing. This adds an additional step to pull over the prisma files when building the run container
In order to test this you must have docker installed and running and then run the following command:
`docker build . -f build/docker/Dockerfile.backend --target run -t api:run-candidate`
The build should complete successfullly
> fix: update backend docker

- sites/public/__tests__/components/applications/StatusItem.test.tsx
- sites/public/src/components/account/StatusItem.tsx
- sites/public/src/pages/account/StatusItemWrapper.tsx
This PR addresses #704
Hides "view application" button on `/account/applications` when listing is closed.
File application, it should show `view application` button on `/account/applications`. Close listing, the button should be hidden.
> fix: remove view listing button from closed listings

- api/src/services/application-flagged-set.service.ts
- api/test/unit/services/application-csv-export.service.spec.ts
- api/test/unit/services/application-flagged-set.service.spec.ts
Pulls the following commit from core
* 64f366d68 - fix: only set build rule for afs if name exists (#4145)
> fix: only set build rule for afs if name exists (#4145)

- doorway-ui-components/src/global/forms.scss
This PR addresses #690 
The font size of text and select fields was smaller than body base, causing mobile browsers to zoom in when a field is selected. This resets those font sizes to the base size (aka `1rem`).
**Note:** the styling of form fields in UIC (and Doorway's duplicate) is pretty wonky right now, so this code isn't pretty. We can revisit the issue entirely once the Seeds forms effort starts up.
Check out search, login/signup, and common app on the public site.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very …
> fix: input font size to avoid mobile zoom

- api/README.md
- api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
This test seems to be consistently failing on main: `Testing Permissioning of endpoints as Limited Jurisdictional Admin in the correct jurisdiction › Testing listing endpoints › should succeed for update endpoint & create an activity log entry`
It also fails locally. The test expects a success when trying to update a listing.
It looks like based on line 1171 in `listing.service.ts` and confirmed w Sarah that if a user is not an admin, they are not allowed to change dates on an active listing, and the test was attempting to do so and was failing as forbidden. I updated the data we are sending which includes some randomized values to ensure we are always sending the same dates. I'm not clear how this was passing before, it was failing every time for me and didn't seem flaky.
> test: testing tests

- api/prisma/migrations/14_add_lottery_status_enums/migration.sql
- api/prisma/schema.prisma
- api/prisma/seed-helpers/listing-factory.ts
- api/src/controllers/listing.controller.ts
- api/src/dtos/listings/listing-lottery-status.dto.ts
- api/src/dtos/listings/listing.dto.ts
- api/src/services/listing.service.ts
- api/test/integration/listing.e2e-spec.ts
- api/test/unit/services/listing.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4057)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4057)
Pulls over commit from core:
https://github.com/bloom-housing/bloom/pull/4167
Run migration and run backend in the terminal. Use the swagger open api for the following flows.
Flow 1: Login as an admin, attempt to change the status of a active listing to releasedToPartners, you should receive an error since listing is not closed.
Flow 2: Login as an admin, attempt to change the status of a closed listing to releasedToPartners, you should receive an error since it must be in approved.
Flow 3: Change the status manually in the db to approved, login as an admin, attempt to change the status of a closed listing to releasedToPartners, confirm change was successful, …
> feat: lottery status (released to partners / retracted) (bloom-housing#4167)

- sites/public/src/pages/sign-in.tsx
This PR addresses #727 
With the addition of recaptcha, the determine network error check was accidentally moved to be only under the recaptcha check. This just pulls it outside of that if statement
Make sure you have `SHOW_PWDLESS=TRUE` set in your .env file for public
- When on the public site login page click "use your password instead"
- Enter an email that is not in the system and anything into the password field
- On submit make sure that an error message shows
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small …
> fix: network error for password login

- sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
- sites/partners/src/components/listings/ListingFormActions.tsx
This PR addresses [#4171](https://github.com/bloom-housing/bloom/issues/4171)
Re-adds the post lottery button if the lottery functionality is turned on
Make sure `SHOW_LOTTERY=TRUE` is set in the env file for partners
- Go to the partner site and in a closed listing see that the "Post results" button is there when editing the listing
- Upload results and check that the "preview results" link appears
- Go to the public site and go to the listings page for the above listing. Check that the "Download Results" button is visible
- [] Ran `yarn generate:client` and/or created a migration when required
- Pull the changes down locally and test that the acceptance criteria is …
> fix: add post lottery button when lottery functionality is turned on

- api/prisma/seed-helpers/listing-factory.ts
- api/src/services/application.service.ts
- api/test/integration/application.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
- api/test/unit/services/application.service.spec.ts
- sites/public/src/pages/applications/review/summary.tsx
- sites/public/src/pages/applications/start/choose-language.tsx
This PR addresses https://github.com/metrotranscom/doorway/issues/698
This PR updates the logic on the FE and BE to block application submissions from past due applications and listings that do not have the common application.
Note that these changes collides with a few existing bugs:
1) You'll notice the addToast line is commented out. I discovered a bug while testing this PR that results in infinite re-renders and subsequently, endless toasts. #4181 
2) If you change a listing that had a commonApp and answer no to digitalApp, the commonDigitalApp field remains true. The logic checks for both but I wrote up a ticket here: #4182 
3) application.e2e-spec.ts has significant amounts of duplicate (copy-pasta) code. Particularly in the creation of dtos. Instead, a base dto should be created …
> fix: improve application submission logic (#4179)

- api/prisma/seed-staging.ts
- sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Pulls over the following commit from core:
- [fix: filter ami charts by jurisdition (](https://github.com/metrotranscom/doorway/commit/7c9b7955d3915a80729386a0d575bdc217c8bc92)https://github.com/bloom-housing/bloom/pull/4177[)](https://github.com/metrotranscom/doorway/commit/7c9b7955d3915a80729386a0d575bdc217c8bc92)
This is for ticket [#4174](https://github.com/bloom-housing/bloom/issues/4174)
> fix: filter ami charts by jurisdition (#4177)

- sites/public/src/lib/customScripts.ts
- sites/public/src/pages/_app.tsx
Google Analytics stopped working for Doorway at the end of May/early June. https://exygy.slack.com/archives/C02G1S19QA2/p1719945449278659. I am not sure how we were able to get data before then as I know google turned off UA integration. Maybe it was a slow roll out and it finally got to us. But this PR uses the styling of HBA to add the google analytics script tags to the site.
When running this locally make sure you have a google analytic tag set for the public site `GTM_KEY=G-XXXXXXXXXX`
Load the public site and go to a few pages, make sure that there is a network call to `https://www.google-analytics.com/g/collect` with the above google tag
- Pull the changes down …
> fix: update google analytics to use ga4 syntax

- api/package.json
- api/prisma/seed-staging.ts
- api/src/controllers/script-runner.controller.ts
- api/src/dtos/script-runner/data-transfer.dto.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
- api/yarn.lock
- shared-helpers/src/utilities/formKeys.ts
- sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
This PR addresses [#715](https://github.com/housingbayarea/bloom/issues/715)
Initial script for moving over data from SMC. This adds two scripts, one for copying over the base jurisdiction data such as AMI charts and preferences and the other is for copying over listings/units.
Notes:
- Images and lottery results will be manually ported over by product. That way the images will be moved to s3.
- Requested approver field is not going to get ported over since this doesn't port over the users at this point. Talked with product and that is ok with them.
This is how I've been testing it:
- Do a reseed locally
- Start up the app locally and go to the swagger api `http://localhost:3100/api`.
- Login via the api to the admin account `http://localhost:3100/api#/auth/login`.
- Go to Heroku and get …
> fix: add hba jurisdiction data transfers

- sites/public/src/tsx_content/housing-help-cards.tsx
This PR addresses #746 
Fixes the link for Contra Costa.
Visit the Help Center > Housing Help page and verify the link works under Immediate Housing Assistance > Contra Costa County.
> fix: use working link for Contra Costa in Immediate Housing Assistance

- sites/public/src/components/shared/FormSummaryDetails.tsx
- sites/public/src/pages/applications/financial/vouchers.tsx
This PR addresses #751 
When you get to the Common App question about Section 8 vouchers, etc., you'll see that if you select None of the above, it deselects the other options—and when you select one of those, None is deselected.
Fill out Common App, verify the option selection
> fix: ensure mutually-exclusive "none" option for Vouchers question

- api/prisma/seed-helpers/unit-factory.ts
Seed data bug was introduced in https://github.com/metrotranscom/doorway/pull/760. toPercision makes a string with `e+` which causes a problem in the partners portal. Switching to toFixed instead to limit decimals but not introducing other string characters.
Run `yarn setup`. Check `units` table in the db or run partners portal and check the seeded listing units.
> fix: monthly rent seed data

- api/src/services/listing.service.ts
This PR addresses #720
A bug fix for the availability type filter. Previously, a listing would only show for open waitlist if it also specified a number of available spots on the waitlist. With this change, if a listing selects the waitlist review order type, it will show.
Add or update a listing to have the waitlist review order and ensure it shows on the frontend when the open waitlist filter is selected.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the …
> fix: availability filter

- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
This PR addresses [#(4122)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4122)
Releases: https://github.com/bloom-housing/bloom/pull/4219
Using each language, change the email address in the public Account Settings page and verify the new copy appears in the alert.
> release: change email update copy

- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
- shared-helpers/src/views/layout/AlertBanner.tsx
- sites/public/src/layouts/application.tsx
This PR addresses [#(779)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/779)
Doorway needs an alert banner for tomorrow's maintenance.
Add `MAINTENANCE_WINDOW=2024-08-07 10:00 -07:00,2024-08-08 8:00 -07:00` to public env file. View public sight and confirm banner is present in all languages.
> feat: doorway infra release - banner

- sites/partners/__tests__/pages/listings/lottery.test.tsx
- sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses [#(4058)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4058)
Releases https://github.com/bloom-housing/bloom/pull/4239
Sign into Partners as a admin, navigate to a closed listing opted into lottery, go to lottery tab, click Run Lottery. Should match image below.
> release: remove errant lottery copy

- build/docker/Dockerfile.backend
The doorway pipeline failed because of a dependency mismatch. Specifically the package 'cheerio' (brought in via 'juice') needs at least node version 18.17 and we are on 18.14.
This PR updates it to the latest 18 version. We could upgrade to 22, but that would be a bigger change so for now just updating the minor version.
To test:
- Have docker desktop installed and running on your machine
- update your .env file for the api to have `DATABASE_URL=postgres://morganludtke@docker.for.mac.host.internal:5432/bloom` with `morganludtke` replaced with your machine's name
- build the docker image with this command `docker build . -f build/docker/Dockerfile.backend --target run -t api:run-candidate`
- This is the step that is currently failing. So having this PR locally should successfully build
- …
> fix: update node to 18.20

- api/src/dtos/listings/listing-update.dto.ts
- api/src/dtos/listings/listing.dto.ts
- api/src/utilities/lottery-date-validator.ts
- api/test/unit/utilities/lottery-date-validator.spec.ts
- sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
- sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
This PR addresses [#(4212)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4212)
Release https://github.com/bloom-housing/bloom/pull/4250
Create or edit a listing in the partners portal.
Save with First Come First Serve selected. No errors should appear.
Edit and save with Lottery selected and No selected for optin. No errors should appear.
Edit and select Yes for optin. Do not fill out start date, start time and end time fields. Error should appear and fields should be highlighted. Cancel edit.
Edit and select Yes for optin. Fill out some but not all of the fields. Error should appear and fields should be highlighted. Cancel edit.
Edit and select Yes for optin. Fill out all of the fields. Save and no errors should appear.
Edit and remove …
> release: require lottery date time fields

- sites/public/src/components/listings/search/ListingsSearch.module.scss
- sites/public/styles/overrides.scss
This PR addresses https://github.com/metrotranscom/doorway/issues/756#issuecomment-2302924630
There was a z-index ordering issue between the filter bar and tags in the listings list. This fixes those orderings.
Verify you can scroll up and down the listing list and all the content disappears under the filter bar.
> fix: z-index issues related to the filter bar

- api/prisma/seed-helpers/listing-factory.ts
- api/prisma/seed-staging.ts
- api/src/controllers/script-runner.controller.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4258)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4258)
Releases: https://github.com/bloom-housing/bloom/pull/4267
Reseed local database. By default, there should be 2 lottery listings. If you check the db, they will have lotteryOptIn set to `null`. Login as an admin and go to the API UI. Call the `optOutExistingLotteries` script endpoint. You should see 2 printed in the console. Check the database to verify the correct listings have been updated.
- Either (1) explicitly ask a clarifying question, (2) request changes, or …
> release: opt out existing lotteries

- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
- shared-helpers/src/views/address/FormAddressAlternate.tsx
- shared-helpers/src/views/multiselectQuestions.tsx
- sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
- sites/public/src/pages/account/edit.tsx
- sites/public/src/pages/applications/contact/address.tsx
- sites/public/src/pages/applications/contact/alternate-contact-contact.tsx
- sites/public/src/pages/applications/contact/alternate-contact-name.tsx
- sites/public/src/pages/applications/contact/alternate-contact-type.tsx
- sites/public/src/pages/applications/contact/name.tsx
- sites/public/src/pages/applications/household/member.tsx
- sites/public/src/pages/create-account.tsx
This PR releases #4260 
This PR updates the length validation on Zip Code fields to be 10 which matches the verify endpoint length. This also updates the error message be take in the length rather than hardcoding 64 characters.
This can be tested by attempting to fill out the application and zip code field with more than 10 characters and seeing the appropriate error message.
> fix: update length requirement and error messaging (#4261)

- sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #4300 
This PR completes an outstanding todo to include the releaseDate in the partners messaging seen in the issue description. It also handles the case of releasing and retracting by finding the most recent release date.
This can be tested by creating a lottery listing as an admin and releasing that lottery. Then as a partner user see the date and time reflected in the lottery publish card. You can also test retracting and releasing the lottery to see the time updated.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if …
> fix: add releaseDate to partner card (#4315)(release)

- sites/partners/cypress/e2e/default/03-listing.spec.ts
- sites/partners/cypress/e2e/default/09-lottery.spec.ts
- sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
- sites/partners/cypress/support/commands.js
- sites/partners/cypress/support/index.d.ts
Pulls over the below commit from core
> test: flaky cypress listing search (#4335)

- ci/buildspec/build_partners.yml
Forgot to include LOTTERY_DAYS_TILL_EXPIRY env var in partners docker file when releasing to Doorway.
> fix: add missing env var

- sites/partners/src/components/shared/ExportTermsDialog.tsx
- sites/partners/src/pages/listings/[id]/applications/index.tsx
- sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses #4299
This PR forces a partner user to check a box confirming that they understand the terms of downloading a lottery export.
This can be tested by attempting to export a lottery as a partner user and attempting to export without/with the agreed to terms checkbox selected.
> fix: lottery export terms checkbox

- sites/partners/src/components/listings/ListingFormActions.tsx
Doorway admin were not able to upload lottery results for listings that opted out of the partner lottery
this changes it so that that option is once again available
- create or edit a listing such that it is a lottery listing, and opt out of the partner lottery
- close the listing
- go back in to edit the listing, you should now be able to upload lottery  results with the "Post Results" option
> fix: nonpartner lottery results can now be uploaded

- sites/public/src/pages/account/application/[id]/lottery-results.tsx
This PR addresses [#4347](https://github.com/bloom-housing/bloom/issues/4347)
Adds links to the help center content on the lottery results page.
Ensure the links go to the help center lottery section. Per [accessibility guidelines](https://www.w3.org/TR/WCAG20-TECHS/G200.html), they don't open in a new tab.
> fix: add lottery help center links to lottery results

- doorway-ui-components/src/page_components/help-center/DoorwayLinkableCardGroup.tsx
- sites/public/src/tsx_content/questions-cards.tsx
This PR addresses [#(insert-number-here)](https://exygy.slack.com/archives/C02G1S19QA2/p1727724477064559)
When trying to hit the Frequently Asked Questions page an error is getting thrown. https://housingbayarea.mtc.ca.gov/help/questions (Page not found in production but an actual error in local development)
This only happens when the `SHOW_PUBLIC_LOTTERY` env variable is not set or set to false
Either set the `SHOW_PUBLIC_LOTTERY` env for the public site to FALSE or remove it entirely from the file.
go to http://localhost:3000/help/questions and the page should fully load
- Either (1) …
> fix: faq page fix

- api/src/services/lottery.service.ts
- api/test/unit/services/lottery.service.spec.ts
This PR addresses [#(4310)](https://github.com/bloom-housing/bloom/issues/4310)
Releases [fix: history log fix](https://github.com/bloom-housing/bloom/pull/4353)
For a lottery listing, close the listing and check it it appears in the history log. Make a change and save it to the listing, a new log should not be present. Reopen the listing, close the listing again, a new log should appear. All lottery related logs should still function as expected.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if …
> release: history log fix

- sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
This PR addresses #4360 
This PR updates the defaultSelected Logic within the "Select Preference" drawer to match on id rather than text to handle multiple preferences with the same name.
Run locally, Log in to partners as an admin, Add preferences with the same name or make multiple copies of existing preferences, Add only some of the preferences with the same name to the listing, Save, Go back to Edit and view the preferences, and only the ones you selected will show as checked. Previously, all with the same name would show as selected.
- Either (1) explicitly ask a clarifying question, (2) …
> fix: match pref on id (#4372)

- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
This PR addresses #4193
When testing the latest user and application import script for SMC a bug was found. The staging and production database has slightly different null constraints on the table "applications" so when trying to insert an application the field `contact_preferences` is required whereas it isn't locally.
Also a log of each application was accidentally kept in the code
The same steps as the previous PR still apply here:
- Do a reseed locally
- Start up the app locally and go to the swagger api http://localhost:3100/api.
- Login via the api to the admin account http://localhost:3100/api#/auth/login.
- Go to Heroku and get the DB credentials for the HBA staging environment https://data.heroku.com/datastores/fd968c98-f208-4066-b8cf-7d3a6bf8ff03#administration
- Use the …
> fix: add required field for applications in script

- api/src/controllers/script-runner.controller.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses #4193
When running the last SMC transfer script of user migration it stopped after only migrating 2 public users without any errors. This happened because for the second user there was an application that wasn't for SMC. The previous code had a "return" statement to avoid adding that application but it accidentally returned out of the whole function.
This PR does the following to remediate the problem:
- splits the existing transfer script into two separate scripts so that we can run just the public user portion
- Changes the code that had the problem so that it just skips the application create but continues on with the rest of the script
- Update unit test to cover that scenario
- Add additional logging so that we can see the progress as the script runs. Tests also …
> fix: split out scripts and fix public transfer script

- api/src/controllers/listing.controller.ts
- api/src/dtos/listings/listing-map-marker.dto.ts
- api/src/services/listing.service.ts
- api/test/integration/api-key-guard.e2e-spec.ts
- api/test/integration/listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
- api/test/unit/services/listing.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(889)](https://github.com/metrotranscom/doorway/issues/889)
Creates a public endpoint to return the id, longitude, and latitude of every open listing called `mapMarkers`.
The existing list endpoint will be used with view params to handle the other endpoint case.
Using OpenAPI or by hitting the API directly through another client, call `listings/mapMarkers`
Verify only open listing id's are returned and check the lat and long returned matches what is in the db.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are …
> release: map marker endpoint (#4453)

- api/package.json
this locks the version of casbin to a specific version that should (hopefully) fix the error in doorway staging
> fix: fixes casbin error

- api/src/services/listing.service.ts
- api/test/unit/services/listing.service.spec.ts
NOTE that this will be pulled back into core
This PR addresses #773 
During Qa, it was discovered that the publishedAt date was showing as none for many open listings. This was because we were not covering the case where a user publishes a listing from scratch, never first saving it as a draft.
Create a listing from scratch and publish it without saving it as a draft. In the partner's listing table, you should see today's date.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to …
> fix: set publishedAt during create

- sites/partners/src/pages/listings/[id]/applications/index.tsx
This PR addresses #950 
Hides expiry line if listing is not closed
This can be tested by looking at the applications export of an open listing and seeing that the expired string is hidden.
> fix: add conditional rendering

- api/src/passports/mfa.strategy.ts
- api/src/passports/single-use-code.strategy.ts
- api/src/utilities/passport-validator-utilities.ts
- api/test/unit/passports/passport-validator-utilities.spec.ts
This PR addresses #4473 
This PR changes the function isUserLockedOut to return the verified failedLoginAttempts count explicitly. Before, it was failing to reset after the lockout period was over because of an assumption that it was pass by reference rather than value.
Note that there is an existing bug in core: https://github.com/bloom-housing/bloom/issues/4284
This can be tested locally by locking out a public user via 5 failed password attempts (you'll have to verify in network tab). Then, go into the DB and set that user's last login at date to be last year. Lastly, try to log in again with an incorrect password and see that the count has been reset (via the network tab).
- Review the code itself from a style …
> fix: return updated failed login attempts (#4474)

- api/src/services/email.service.ts
- api/src/services/listing.service.ts
- api/src/services/lottery.service.ts
- api/test/integration/listing.e2e-spec.ts
- api/test/integration/lottery.e2e-spec.ts
- api/test/unit/services/email.service.spec.ts
- api/test/unit/services/listing.service.spec.ts
- api/test/unit/services/lottery.service.spec.ts
- yarn.lock
This PR addresses #873 
This PR sends emails via 'bcc' rather than the 'to' field in order to hide the other recipients of the email. My research showed that the options are simple: use the bcc field to send in bulk or loop through each email and send individually. I've included some resources below mentioning the use of the bcc field. Both implementations are straightforward but I worried that sending emails individually could lead to serious performance issues. I also heard mentions of this approach requiring queuing systems which seemed out of scope. The risk of the bcc approach is that the empty "to" field is more likely to be flagged as suspicious so a dummy email like "doorway-applicant@example.com" could be used to help address that concern... though seemingly not entirely. …
> fix: hide other recipients

- api/src/utilities/lottery-date-validator.ts
- api/test/unit/utilities/lottery-date-validator.spec.ts
This PR addresses #936 
This PR updates the lottery date validation process to require the lottery date whether the user has opted in or not.
This can be tested by attempting to save a lottery listing that opted out of using the system lottery with missing lottery date information. 
> fix: remove opt in logic

- api/src/services/listing.service.ts
This PR addresses #4490
This PR updates the duplicate function in the listing service to transform the application methods array to how the listing create function expects it. 
Test copying a listing with no paper app, paper app selected but not uploaded, one paper app, multiple paper apps... and ensure that the listing and assets are copied over without error.
> fix: handle copying app methods (#4491)

- api/prisma/seed-helpers/feature-flag-factory.ts
- api/src/controllers/feature-flag.controller.ts
- api/src/dtos/feature-flags/feature-flag-associate.dto.ts
- api/src/dtos/feature-flags/feature-flag-create.dto.ts
- api/src/dtos/feature-flags/feature-flag-update.dto.ts
- api/src/dtos/feature-flags/feature-flag.dto.ts
- api/src/dtos/jurisdictions/jurisdiction-update.dto.ts
- api/src/dtos/jurisdictions/jurisdiction.dto.ts
- api/src/modules/app.module.ts
- api/src/modules/feature-flag.module.ts
- api/src/permission-configs/permission_policy.csv
- api/src/services/feature-flag.service.ts
- api/src/services/jurisdiction.service.ts
- api/test/integration/feature-flag.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
- api/test/unit/services/feature-flag.service.spec.ts
- api/test/unit/services/jurisdiction.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses [#(4459)](https://github.com/bloom-housing/bloom/issues/4459)
Creates the module, controller and service files for the new Feature Flag table. Allows for standard CRUD methods, as well as a list endpoint and an endpoint to add/remove jurisdiction associations with the flag (`associateJurisdictions`). Permissions are limited to admin only. Flags associated with jurisdictions will appear when jurisdiction data is returned.
Start up the backend. Login as an admin, either through the API or partners portal. Test each endpoint:
- Create a feature flag
- Get the feature flag using the id returned ^^
- Update the feature flag using the id
- Get the feature flag to verify update
- Associate jurisdiction(s) with the flag
- Get the feature flag to verify association
- Get the …
> release: feature flag consumption

- sites/partners/src/pages/listings/[id]/index.tsx
This PR addresses #943 
This PR updates the lottery tab logic to not show if the user is a limited juris no PII user.
This can be tested by signing in to a limited juris user and viewing a closed lottery listing. There should be no lottery tab visible. Now check out that same listing with other roles and it should still be visible.
> fix: check for limited juris role

- sites/partners/src/lib/applications/formatApplicationData.ts
Will allow partial date formatting on the two paper application date fields.
Try to update a paper application with a partially formatted date (i.e. with single integers in month and day, like `1/5/2024` vs `01/05/2024` and ensure the data is saved
> fix: partial date formatting on paper app

- api/src/controllers/script-runner.controller.ts
- api/src/services/application.service.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
- sites/partners/src/lib/applications/formatApplicationData.ts
This PR addresses [#(977)](https://github.com/metrotranscom/doorway/issues/977) [#(975)](https://github.com/metrotranscom/doorway/issues/975#event-15551490203)
Due to removal of the `Work in city` question from all applications, an unintended bug was created when updating paper applications.
To correct this, the application update function will no longer automatically create a work address for the household members and the applicant.
The existing applications that are affected by this issue need to have the `work_address_id` field cleared from the applicant and householdMembers tables. This is handled by the new script that collects the applicants and householdMembers that have work_address_id's, nulls these fields, and then deletes the empty addresses from the address table.
On the main …
> fix: paper application saving issue

- api/src/services/email.service.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/980
listing opportunity email now has dates transformed into the correct timezone
locally: after seeding make sure you turn on the listing opportunity jurisdiction setting to get the email
create a listing with an application due date -> publish listing -> you should get an email with the correct date
> fix: timezone apply to opp email

- api/src/services/application.service.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/application.service.spec.ts
- api/test/unit/services/script-runner.service.spec.ts
This PR addresses [#(977)](https://github.com/metrotranscom/doorway/issues/977)
Due to SQL limit of 32767 for items in the where clause, the updateMany and deleteMany calls failed on staging data.
To account for this, updateMany for applicants and householdMembers is switch to checking which record have a workAddressId and the deleteMany for address uses batching on the addressIds.
Additionally, a bug was found in staging that paper and electronic applications were not saving because the contactPreferences were not being sent. Corrected by always setting it to `[]`
Run yarn setup
View db tables `applicant`, `household_member` and `address`. Seed data adds work addresses to a number of applicants and household members.
Run the script /scriptRunner/removeWorkAddresses
Check the tables again …
> fix: batch deletion for remove work address script

- build/docker/Dockerfile.backend
Switching to symlink instead of apk add. Based on https://github.com/nodejs/docker-node/issues/2175#issuecomment-2530130523
Run docker build . -f build/docker/Dockerfile.backend --target run -t api:run-candidate locally and see that the following warning is not present:
`prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.`
To view logs, open link provided after build completes in the browser.
- Either (1) …
> fix: docker symlink

- sites/public/src/pages/applications/start/autofill.tsx
This PR temporarily turns autofill off based on [this Slack support issue](https://exygy.slack.com/archives/C02G1S19QA2/p1734480633580029).
Ensure you don't hit the autofill page after already submitting an application.
Partially addresses #1016 
> fix: turn off autofill

- api/src/controllers/listing.controller.ts
- api/test/integration/listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-correct-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-limited-juris-admin-wrong-juris.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
- api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
- api/test/unit/services/listing.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
- sites/partners/src/lib/hooks.ts
- sites/partners/src/pages/index.tsx
This PR addresses #1014
The partners list was no longer filtering by jurisdiction. The cause was that for the map, we changed the structure of the combined list to send filter parameters in the body, which updated some of the swagger for the filters, but we didn't update the generic list to send parameters in the body as well.
Create a partner and assign them only to some jurisdictions / listings. Ensure they only see those listings in the list.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you …
> fix: partners seeing all listings in list

- sites/partners/src/components/settings/PreferenceDrawer.tsx
This PR releases https://github.com/metrotranscom/doorway/issues/1004
This PR updates the watch function to include a default value. The issue was that we were defaulting the canYouOptOutQuestion to true on all preferences that didn't explicitly set to no but depending on the watch value to be Yes in order to show the optOutText field. As a result, the watch value was undefined on load and wouldn't set to Yes until the user directly interacted with the radio leading to the confusing experience described in ticket. This one line change handles that case. 
This can be tested by editing existing preferences and adding new ones. In both cases, if the canYouOptOutQuestion shows yes, the optOutText field should be visible
- …
> fix: set optOut watch default value (#4512)

- api/prisma/seed-staging.ts
- sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
This PR addresses #984
There is an intermittent issue where when you go to a listing edit page and open a unit drawer, if the unit has an ami chart selected that is not first in the list - sometimes the unit drawer will load with the first ami chart selected anyway.
The new seed has multiple ami charts. Create a listing with a unit that has an ami chart selected that is not the first chart that appears in the dropdown. Re-open the edit page and open the unit drawer and ensure the proper ami chart is selected.
Will backport the fix to core.
- Either (1) explicitly ask a clarifying question, …
> fix: ami chart selection bug

- api/src/services/listing-csv-export.service.ts
This PR addresses #1027 
The listing units csv export is displaying the incorrect AMI Chart percentage. It is grabbing the first value from the amiChart instead of getting the percentage off of the unit table
Note:
- There are currently no tests that cover this part of the code and we should add those as a separate issue
- A separate PR will be created in core and HBA
After a clean reseed In the partner site click the "Export to CSV" button on the listings page and compare the values to the listings
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, …
> fix: use correct ami percentage in csv

- sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
- sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
- sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
This PR addresses [#977 ](https://github.com/metrotranscom/doorway/issues/977)
This PR updates the deleteModal open logic to handle an orderId=0. When a user applies online, the first household member is set to an OrderId of 0 but when added via the partner's side, it adds it with an orderId of 1. This PR also updates the ordering on the partner's side so that a user sees the household members in the order they added them (public side is already demonstrating this behavior). However, I stopped short of refactoring the orderId to be used more consistently to avoid any risks in conflicting with existing data. Instead, that work is captured here: https://github.com/bloom-housing/bloom/issues/4511
Note: I had originally assumed the orderId was null causing this issue but querying production …
> fix: household member delete + order (#4510)

- api/src/services/application-exporter.service.ts
- api/test/unit/services/application-exporter.service.spec.ts
This brings over the following Core PR:
* bloom-housing/bloom#4464
> release: export lottery with sorted preferences by ordinal

- api/src/utilities/application-export-helpers.ts
- api/test/unit/utilities/application-export-helpers.spec.ts
- shared-helpers/__tests__/formKeys.test.ts
- shared-helpers/src/utilities/formKeys.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1009
The ticket also mentions cleaning up the instances where doorway entered a space to get the "other" field to save which this PR doesn't cover.
This PR includes two different empty string checks in the formKeys file which prevents the selection of other without entering further information from being filtered out or being stored with a colon and space. 
This can be tested by 
a) submitting an online app with a mix of demographic data (including other selections without any text inputted) and going to the partners portal to see that it was stored correctly
b) submit a **paper** app to the same listing with a unique mix of demographic data also including empty other selections and then edit this paper app multiple times …
> fix: handle empty other race options (#4513)

- api/src/services/listing.service.ts
- api/src/services/user.service.ts
- api/test/unit/services/listing.service.spec.ts
This PR addresses [#(1035)](https://github.com/metrotranscom/doorway/issues/1035)
Jurisdictional Admin - No PII accounts are not receiving `Forgot password` or `Approved and published` emails.
This is cause the user role was not added to the partner forgot password or the listingApprovalNotify flows.
Corrected by added the user role to both.
- Create a  Jurisdictional Admin - No PII account using an admin account.
- Confirm the account and sign in.
- Create a new listing and submitted it
- Sign out
- Try Forgot Password flow, confirm email is received
- Sign in as an admin again
- Navigate to Pending listing
- Request changes, confirm email is received
- Approve and publish, confirm email is received
- Review the code …
> fix: Jurisdictional Admin - No PII account emails

- sites/partners/next.config.js
Release caused SHOW_SMS flag to be turned on by default, switching default back to false
Partner Portal should not show SMS option
> fix: default sms to false

- api/src/services/application-exporter.service.ts
- api/src/services/email.service.ts
- api/src/utilities/application-export-helpers.ts
- sites/partners/src/pages/application/[id]/edit.tsx
This PR addresses: [This slack thread](https://exygy.slack.com/archives/C01Q4QG5R8Q/p1736794614377889) and [This comment](https://github.com/metrotranscom/doorway/issues/995#issuecomment-2587789072) 
Due to bad data in staging there are a few listings where there is non applicant attached to applications. When a user attempts to export the applications for the listing these are tied to it crashes the backend.
This PR adds a null check to make sure if this data exists it won't break anything
Also there was a missing space in the updated content of the rental opportunity email
Have an application and remove the applicant_id from it in the db. You should then be able to properly export the applications.
This is blocking the release so no tests have been created, but long term we should add …
> fix: add null check for csv export

- api/src/utilities/application-export-helpers.ts
This PR addresses [#(4536)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4536)
For preferences that required an address to be input, they were appearing for the application export but not for the lottery export. This adjustment allows it to work correctly for both.
On the partner site, create/update a listing to be a lottery listing with a preference that requires/allows for an address to be input.
Submit an application for the listing, claim the preference and include an address.
Export applications and verify the preference and preference address appear correctly.
Close the listing, run the lottery, export the lottery, and verify the preference and preference address appear correctly.
- Ensure the author …
> release: include preference address (#4537)

- api/src/dtos/shared/base-filter.dto.ts
- api/src/services/listing.service.ts
- doorway-ui-components/src/forms/Field.scss
- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
- shared-helpers/src/types/backend-swagger.ts
- shared-helpers/src/utilities/regex.ts
- sites/public/src/components/listings/search/LandingSearch.module.scss
- sites/public/src/components/listings/search/LandingSearch.tsx
- sites/public/src/components/listings/search/ListingsSearchCombined.tsx
- sites/public/src/components/listings/search/ListingsSearchModal.tsx
- sites/public/src/components/listings/search/ListingsSearchModalDeprecated.tsx
- sites/public/src/lib/listings/listing-query-builder.ts
- sites/public/src/lib/listings/search.ts
This PR addresses #938 
This PR adds the FE property name search fields as well as the BE support to search by text on the listings combined fields. There is existing search functionality for the listings table but since the public side uses the combined table, this new approach had to be added. Also, you'll notice custom handling of the semicolon and colon character because of their use in our url formatting and the single apostrophe since it could break the sql query respectively.
Also, flagged some a11y concerns that seem to be bigger than this implementation here: https://github.com/metrotranscom/doorway/issues/1045
Outstanding question
1. I previously had all inputs cleaned with regex like .replace(/[^a-zA-Z0-9:;"' -]/g, "") but was feeling frustrated on how this would interact with …
> feat: property name search

- shared-helpers/src/views/sign-in/FormSignIn.module.scss
- shared-helpers/src/views/sign-in/FormSignInDefault.tsx
- shared-helpers/src/views/sign-in/FormSignInPwdless.tsx
This PR addresses #965
This PR ensures the "Forgot password?" link on the username/password sign in flow retains whichever is the current locale.
Check the link when attempting to sign in.
> fix: switch to Link component from Seeds on forgot password

- sites/partners/src/lib/listings/UnitsFormatter.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1059 and https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4220
This PR saves Studios and SROs to have zero bedrooms rather than null bedrooms. This doesn't change much in core but it is critical for filtering in doorway which is a feature core will likely get soon.
After merge, I will be running the following query in Core, HBA, and Doorway since querying existing data showed that all null bedroom units were Studios or SROs
`Update units set num_bedrooms=0 where num_bedrooms is null;`
This can be tested by creating SROs and Studios on the partner side and then checking the units table to ensure they are saved as zero rather than null number of bedrooms.
- Read and understand the …
> fix: set studio + sro to zero bedrooms (#4611)

- sites/public/src/components/listings/search/ListingsSearchModalDeprecated.tsx
This PR is a follow up from #972 
This PR adds the search field to the deprecated modal so that whether the new map is enabled or not, the search is functional.
This can be tested by changing the SHOW_ALL_MAP_PINS flag to false and testing the search field in the modal.
> fix: search field without flag

- sites/public/src/components/listings/MapClusterer.tsx
This PR addresses #1074
Following the map release, given the specific data set we have in production, we're less satisfied with the cluster sizes compared to what was in staging. The cluster sizes feel as though they are not big enough compared to a single pin, and there's not enough disparity between clusters of different numbers. Google has a few different algorithms you can use for clustering.
I updated some settings on one of their algorithms and increased slightly both the size and disparity between clusters.
This has been approved w design. 
This PR with updated cluster algorithm and slightly larger size and disparity:
Production:
- Pull the changes down locally …
> refactor: update sizes of clusters

- shared-helpers/src/locales/es.json
- shared-helpers/src/locales/general.json
- shared-helpers/src/locales/tl.json
- shared-helpers/src/locales/vi.json
- shared-helpers/src/locales/zh.json
- sites/public/src/components/listings/ListingsCombined.module.scss
- sites/public/src/components/listings/ListingsCombined.tsx
- sites/public/src/components/listings/ListingsList.tsx
- sites/public/src/components/listings/ListingsMap.tsx
- sites/public/src/components/shared/MapControl.module.scss
- sites/public/src/components/shared/MapRecenter.module.scss
- sites/public/src/components/shared/MapRecenter.tsx
- sites/public/styles/overrides.scss
This PR addresses #1068
We currently have a confusing state in the map where you might be zoomed in on a single visible pin, and then change some filters that actually increase the number of pins on the map, but if those pins are not in view where you're zoomed into, it looks like nothing changes.
We currently only show the recenter map button in the listings list if there are zero pins visible.
Here, we move the recenter button to the map, and show it if there are ever pins not currently visible on the map - not just if we currently have zero. It will appear on both desktop and mobile in the top right section of the map.
Ensure the button shows on the map if there are ever pins not in view, on desktop and mobile, and that clicking it recenters the view. …
> feat: move recenter button to map

- api/prisma/seed-staging.ts
Has the dev build create 100 admin users to allow for more concurrent users during a perf test
> feat: 100 admin users in the dev environment for perf testing

- api/src/controllers/application.controller.ts
- api/src/controllers/lottery.controller.ts
- api/src/services/application-exporter.service.ts
- api/src/utilities/zip-export.ts
- api/test/unit/services/application-exporter.service.spec.ts
- sites/partners/src/lib/hooks.ts
- sites/partners/src/pages/api/adapter/[...backendUrl].ts
- sites/partners/src/pages/listings/[id]/applications/index.tsx
- sites/partners/src/pages/listings/[id]/lottery.tsx
This PR addresses [#(4370)](https://github.com/bloom-housing/bloom/issues/4370)
Generalized zip exporting code to allow for applications export to be zipped.
With a listing that has applications, go to the applications tab.
Export the applications.
Confirm export was a zip file.
Open zip file, confirm csv is created.
Open CSV file and check contents.
Edit listing to be a lottery.
Run lottery.
Export lottery.
Confirm export was a zip file.
Open zip file, confirm XSLX is created.
Open XSLX file and check contents.
Bring down the app.
Change `APPLICATION_EXPORT_AS_SPREADSHEET` to TRUE in the sites/partners/.env file.
With a listing that has applications, go to the applications tab.
Export the applications.
Confirm export was a zip file.
Open zip file, confirm XSLX is created.
Open XSLX file …
> release: refactor and extend zip code (#4588)

- api/prisma/seed-staging.ts
- api/src/controllers/script-runner.controller.ts
- api/src/services/script-runner.service.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1056
This creates a new script runner endpoint to reset all the non-english translations 
This is going to take some time to double check but: run the new script runner locally. Double check that each of the strings: https://docs.google.com/spreadsheets/d/1aFoUc76C44SInzrac02cvG7UhxfLVyHoGwds6fmzqNA/edit?gid=481259231#gid=481259231 are in place and replacing the correct english string
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if …
> feat: add script runner to reset email translations

- sites/public/src/components/listings/ListingsCombined.module.scss
- sites/public/src/components/listings/ListingsCombined.tsx
- sites/public/src/components/listings/ListingsList.tsx
- sites/public/src/components/listings/ListingsMap.tsx
- sites/public/src/components/listings/MapClusterer.tsx
- sites/public/src/components/listings/search/ListingsSearchCombined.tsx
- sites/public/src/components/shared/MapRecenter.tsx
- sites/public/src/pages/listings.tsx
This PR addresses #1078
It is challenging to reproduce and I cannot do so consistently, but on a throttled connection, the listing list will sometimes flash an empty state before the full list has had a chance to actually do its first load.
This PR ensures that on first page load, the loading state persists through a very slow connection until the list has loaded for the first time.
It also tries to protect against a scenario where the google maps API itself loads very slowly, and we potentially are fetching markers and listings before the map has rendered. I don't think this is actually happening for folks though. On the slowest possible throttling w the cache disabled, I still cannot reproduce it.
On both desktop and mobile, throttle your connection in the network tab. Load the page, …
> fix: wait for map load

- api/src/services/script-runner.service.ts
This updates the translation reset script with the following:
- adds translations to the footer of the application confirmation and lottery results emails
- updates a missing translation for Vietnamese for the update email address email
- apply for a listing with an account created in the various languages. Make sure you create an account in each language
- attempt to update the email on the Vietnamese language account and you should get an email in Vietnamese properly translated  
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are …
> fix: updating reset translations from bash

- api/src/utilities/unit-utilities.ts
This PR addresses #4631
The units summarization process was failing to handle multiple units without rent information. The first unit was correctly handled with "t.n/a" in the getDefaultSummary function but then from there the inputs to a minMax function were t.n/a and null leading to the NaN. This fix avoids the minMax comparison if the unit's associated field is null.
Add multiple units of the same unit type to a listing that have no rent or rent as a percentage of income information. Ensure that the unit summary displays with n/a rather than NaN per month.
- Either (1) explicitly ask a …
> fix: null checks in minMax process (#4632)

- api/src/services/email.service.ts
This PR addresses #1063 
Doorway would like the from email address in the "New Rental Opportunity" emails to be from a doorway specific email address. This was created by the govDelivery team, but by default automated sends (like from Bloom) take the organization's default email. This is to change the "from email" to this new email.
Notes:
- The email was just created in the production instance of govDelivery and if you pass an invalid ID in the request, the "sendNow" request fails with a 422 error. This is why the code only adds this new value if it's not "stage" environment.
Unfortunately there is no way to test this in a pre-production environment since that email doesn't exist anywhere else. 
Here is what I did to test this code locally:
- Made sure that it still works with the stage …
> fix: change the from email for gov delivery sends

- sites/public/src/pages/applications/start/autofill.tsx
This PR addresses #1090
Autofill is currently "off", but it should be on!
I'm not sure how the final onSubmit call got in there bc it's not there in core, but it prevents autofill from happening & returns too early.
Ensure locally if you submit an application while logged in that upon starting a second application you are prompted with autofill.
We should pull over the new [autofill Cypress test](https://github.com/bloom-housing/bloom/pull/4607) - it would have caught this.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very …
> fix: autofill bug

- sites/public/src/components/listings/search/ListingsSearchCombined.tsx
This PR addresses [slack thread](https://exygy.slack.com/archives/C02G1S19QA2/p1739471658290209)
When updating the filters on the map view the spinner for the list of listings immediately pops up after submission. However, in the case where the results returned are the same we do not do a backend api call to get the list and the spinner never gets turned off.
This can be seen in a couple of scenarios:
Do two different filter searches and the same results are returned
e.g search "elmwoo" the first time and then "elmwood" the second.
Do the exact same search
Open up the filter click "Show matching listings" without changing any filters
Seed the backend with plenty of listings (you can use yarn db:setup:staging-large)
These are three of the scenarios that should be tested:
1. different …
> fix: loading state

- sites/public/src/components/listings/search/ListingsSearchCombined.tsx
This PR addresses [slack thread](https://exygy.slack.com/archives/C02G1S19QA2/p1739982449113979)
When changing pages in desktop view of the listing search page the listing data is not getting updated. This is because since the map markers don't change when changing pages we are not doing the call to get the new listings
All functionality on the listing search page should be tested.
Primary test:
1. Seed enough listings to have more than one page.
2. Load the [listing search page](http://localhost:3000/listings) and make sure map and listings loads correctly
3. Click into a different page by using the pagination underneath the listings
4. Verify new listings have loaded but map stays the same
Other things that should be tested
1. Moving map and zooming still properly filters the listings. …
> fix: pagination fix for desktop view

- sites/public/src/components/listings/ListingsCombined.module.scss
- sites/public/src/components/listings/MapClusterer.tsx
Addresses the issue noticed in bash [here](https://exygy.slack.com/archives/C01Q4QG5R8Q/p1741025321036199) that the cluster icons are ovals.
Run locally with `yarn setup:large` to get more clusters, and ensure the clusters are circles.
I can walk this back tons of commits and it still happens, so I don't think it was a code change - I wonder if it was an update to the package.
> fix: oval icons

- doorway-ui-components/package.json
- doorway-ui-components/src/page_components/listing/ListingCard.tsx
- sites/public/src/components/listings/ListingsList.tsx
- sites/public/src/components/listings/search/LandingSearch.tsx
This PR addresses #1084
Fixes a few instances of links not persisting the language selection. The issue was with UIC buttons, so I switched them to Seeds buttons. This did slightly update the styles, but in a way that is a bug fix and now is more consistent w the rest of the site and Seeds decisions - the buttons were not styled in the rounded Doorway theme, and were using all-caps.
Ensure the 3 places now persist language:
1. The see listings button on the home page
2. The see details button on the map page (you have to click the button itself, not the image)
3. The help center button underneath the listings on the map page
Prod:
This PR:
Prod:
This PR:
- Pull the …
> fix: language not persisting through navigation

- api/src/services/listing.service.ts
There was an issue with selecting non-english and clicking a map pin on the public site listing map
if the listing wasn't recently translated via the google translation service we were getting a blank pin and an error message
- reseed
- on the public site select a non-english language
- head to the listing map on the public site
- click on the map pin for a listing you'll notice that the pin is working now
- prior to this fix the pin popup would show as empty and an error would be thrown in the api
- the error was that the translation attempt was missing required strings
- Either (1) …
> fix: update to fix pop up translations

- sites/partners/page_content/locale_overrides/general.json
- sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx
This PR addresses https://github.com/metrotranscom/doorway/issues/1189
Removes the alameda and smc reference on the partner's county dropdown side info panel
Log into partners, go to create or edit a listing, scroll down to the county dropdown and you should see the info panel beside it. 
the alameda and smc ref should be removed from there 
> Removing alameda ref

- api/prisma/migrations/24_temp_listing_map/migration.sql
- api/prisma/schema.prisma
- api/src/controllers/script-runner.controller.ts
- api/src/dtos/script-runner/asset-transfer.dto.ts
- api/src/modules/script-runner.module.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1051
This creates a new transfer script runner that transfers over the listing images so we don't have to move those by hand. This pattern can be repeated for each of the other assets
you will need to set up and run through the:
- jurisdiction transfer script
- listing transfer script
- then run this script
This is a paginated transfer so you'll need to run it a few times to get through all the listings, but once thats complete you should be able to head into the partner and public portal and verify that the listing images are all present as they were in the "foreign" db 
- Pull the changes down locally …
> feat: creating new listing image asset transfer script

- api/src/services/script-runner.service.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1216
This adds an order by to the last unordered paginated script runner script for transferring jurisdictional data
You'll need to run the transfer scripts up to and including the asset transfer script (asset transfer script was the only one that got a change)
> fix: adding order by to paginated scripts

- sites/partners/__tests__/components/users/FormUserManage.test.tsx
- sites/partners/src/components/users/FormUserManage.tsx
This PR addresses <bug fix from release bash>
Limited Jurisdiction admin was accidentally removed from the user role drop down in the last release PR
* Log in as an admin and go to the user page http://localhost:3001/users.
* Verify that "Jurisdictional Admin - No PII" is an option in the role field
> fix: add limited jurisdiction admin back

- shared-helpers/src/views/layout/AlertBanner.module.scss
- sites/public/styles/overrides.scss
Two bugs were found in the bug bash of Doorway. Both related to the filter dialog.
1. The "Show matching listings" button is the same color as the footer background
2. The site banner has a higher z-index then the dialog
* The fix for the footer is to revert back to the grayish color that is in production instead of the new blue color
* The fix for the banner is to switch from 99999 as the z-index to 9
Locally you should now see the above mentioned fixes.
Note: you will have to have the `SITE_MESSAGE_WINDOW` env variable set in the public .env file to see the banner
Note: the fix for the grayish footer also carries over to other dialogs such as the agree to terms modal
- Review …
> fix: dialog footer and banner css fixes

- doorway-ui-components/package.json
- shared-helpers/package.json
- sites/partners/package.json
- sites/public/package.json
- yarn.lock
This uptakes the ui-c revert from https://github.com/bloom-housing/ui-components/pull/172
This update will affect phone fields throughout the app but the important fix here is:
- go to an application on the partners site where the applicant has a phone number input
- note it on the application details page
- go in to edit the application
- the applicant phone number field should be present
> fix: uptaking uic change

- api/src/controllers/script-runner.controller.ts
- api/src/services/script-runner.service.ts
- api/test/unit/services/script-runner.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
This PR addresses #(4977)
Script to update the data in regards to the `wasCreatedExternally` columns.
Using a copy of HBA prod data, insert data into db.
Run `yarn db:migration:run` to add doorway specific migrations
Run backend api
Login as admin
Run script `scriptRunner/markTransferedData`
Check in DB that applications, listings and multiselect questions from Alameda and San Mateo are now marked as true in the `wasCreatedExternally` column on the respective tables.
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small …
> feat: portal of origin script

- api/src/enums/listings/view-enum.ts
- api/src/services/listing.service.ts
- api/test/unit/services/listing.service.spec.ts
- shared-helpers/src/types/backend-swagger.ts
- sites/partners/src/lib/hooks.ts
- sites/partners/src/pages/users/index.tsx
Releases the below commit from core
Currently in our smallest testing dynos in Heroku, if we have a good number of listings (currently testing with over 300), you're unable to add a partner user. This is because we are fetching every single listing to be able to show the drawer that has checkboxes for each listing to give access. We are fetching much more data than we need to, and we're running out of memory.
We should instead fetch only the name, id, and jurisdiction.
To test, you should add a new partner user and ensure you can check and uncheck individual listings.
> refactor: fetch less data in partner user drawer (#5014)

- api/src/services/email.service.ts
Last step for the new TAY community type https://github.com/housingbayarea/bloom/pull/848
When sending listing opportunity emails as well as the CSV export, there needs to be a mapping of the community type name to the human readable name. This was missed when adding the TAY community type
The main requirement to test this is to setup a listing that has the new community type set.
Testing the email for listing opportunity is not the easiest, but can be tested by enabling the listing opportunity for a jurisdiction and swapping out the `.govSend` in the `listingOpportunity` function within `email.service.ts` for the `sendSingleSES` function. You will need to enter your own email information for the email to information
Testing the CSV export is much more straightforward, you can just export …
> fix: add tay community type to email

- shared-helpers/src/utilities/photos.ts
- sites/public/__tests__/components/listing/listing_sections/Apply.test.tsx
- sites/public/src/components/listing/ListingView.tsx
- sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
- sites/public/src/components/listing/listing_sections/Apply.tsx
- sites/public/src/components/shared/FormSummaryDetails.tsx
This PR addresses #5080 
This PR addresses the following points in the issue:
1. The fallback image is now utilized. There was a typo creating this bug.
3. The styling is fixed by removing the unnecessary tailwind which allows the overrides to apply correctly. NOTE that this slightly changes the visuals of the core experience but since anything seeds related should be using sans serif and I assume we'd want the h3 headers to align in styling rather than create a custom one off styling for the application, I made the update
You is a example of old styling, Household Details is an example of new styling
4. Mandated accounts should not force a user to sign in if the application is not a common app. This is achieved by pulling a doorway PR back to core (with slight tweaks) …
> feat: bash fixes 1 (#5104)

- api/src/services/script-runner.service.ts
This PR addresses https://github.com/metrotranscom/doorway/issues/1230
During the listing transfer script we were not properly waiting for multiselect question writes, this should fix that
you need to run the transfer scripts up to and including the listing transfer script
> fix: less likely to flood the connection pools

- api/src/services/application-exporter.service.ts
- api/src/utilities/application-export-helpers.ts
- api/test/unit/utilities/application-export-helpers.spec.ts
- sites/partners/__tests__/components/applications/sections/FormDemographics.test.tsx
- sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
This PR addresses #1422 and [This slack message](https://exygy.slack.com/archives/C02G1S19QA2/p1752069802228349)
Doorway would like be able to select "not listed" for spoken language and not be required to enter any additional information in the partner site. The scenario where that is needed is when a paper application comes in with nothing filled in for the "spoken language".
Also a bug was found in the CSV export when you have `APPLICATION_EXPORT_AS_SPREADSHEET` environment variable set to true the "Spoken Language" column is not properly populated
Lastly there is a change here that allows the deselection of a language, gender, and sexual orientation on the paper application if one has been selected
This can be tested by  filling out a paper application and select "Not Listed" for the …
> fix: allow not listed with no language

- sites/public/src/components/listing/ListingView.tsx
This PR addresses [#(5354)](https://github.com/bloom-housing/bloom/issues/5354)
When the "What To Expect" field is not set (aka null) on the partners site, attempting to open the Listing Details page on the public site throws a 404 not found error as the Markdown does not expect null.
These are fixed by checking if there is a value in the "What To Expect" field on the Public site.
Create/Edit a listing on the Partner site. Delete the default text from the "What To Expect" field. Save changes/publish listing.
Go to the above listing on the Public site. Make sure you can see the listing and that no "What To Expect" section is present.
Go back to the Partners site and edit the listing. Add some text into the field.
Back to Public site again. Make sure you can see the text that was added to …
> fix: public 404 error around what to expect

- sites/public/src/components/page/Content404Deprecated.tsx
Previous PR accidentally changed the path of the additional help button on the [404 page](https://housingbayarea.mtc.ca.gov/404).
Cause a 404 error on the public site.
Click on the additional help button
> fix: additional help link correction
